#!/bin/bash
set -eou pipefail
set -a; source .env.local; set +a

. dev/net/k8s-env

secret="$(kubectl get secret --namespace xmtp-system argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode)"
echo -n "${secret}" | pbcopy

echo "Password has been copied to your clipboard"
echo "Open http://argo.localhost/"
