#!/bin/bash
set -eou pipefail
set -a; source .env.local; set +a

. dev/net/k8s-env

secret="$(kubectl get secret --namespace xmtp-tools grafana -o jsonpath="{.data.admin-password}" | base64 --decode)"
echo -n "${secret}" | pbcopy

echo "Password has been copied to your clipboard"
echo "Open http://grafana.localhost/"
