#!/bin/bash
set -eo pipefail

secret="$(kubectl get secret --namespace xmtp-system argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode)"
echo -n "${secret}" | pbcopy

echo "Password has been copied to your clipboard"
echo "Open http://argo.localhost/"
