#!/bin/bash

PLAN=$(source .env.local; echo "$PLAN")
plan_dir="${PWD}/dev/terraform/plans/${PLAN}"

if [ -f "${plan_dir}"/kubeconfig.sh ]; then
    "${plan_dir}"/kubeconfig.sh
fi
export KUBECONFIG="${plan_dir}/.xmtp/kubeconfig.yaml"

alias k=kubectl
alias kn="kubectl -n xmtp-nodes"
alias ks="kubectl -n xmtp-system"
alias kt="kubectl -n xmtp-tools"
