// V3 invite message structure

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        (unknown)
// source: mls/database/intents.proto

package database

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of update to admin lists
type AdminListUpdateType int32

const (
	AdminListUpdateType_ADMIN_LIST_UPDATE_TYPE_UNSPECIFIED        AdminListUpdateType = 0
	AdminListUpdateType_ADMIN_LIST_UPDATE_TYPE_ADD_ADMIN          AdminListUpdateType = 1
	AdminListUpdateType_ADMIN_LIST_UPDATE_TYPE_REMOVE_ADMIN       AdminListUpdateType = 2
	AdminListUpdateType_ADMIN_LIST_UPDATE_TYPE_ADD_SUPER_ADMIN    AdminListUpdateType = 3
	AdminListUpdateType_ADMIN_LIST_UPDATE_TYPE_REMOVE_SUPER_ADMIN AdminListUpdateType = 4
)

// Enum value maps for AdminListUpdateType.
var (
	AdminListUpdateType_name = map[int32]string{
		0: "ADMIN_LIST_UPDATE_TYPE_UNSPECIFIED",
		1: "ADMIN_LIST_UPDATE_TYPE_ADD_ADMIN",
		2: "ADMIN_LIST_UPDATE_TYPE_REMOVE_ADMIN",
		3: "ADMIN_LIST_UPDATE_TYPE_ADD_SUPER_ADMIN",
		4: "ADMIN_LIST_UPDATE_TYPE_REMOVE_SUPER_ADMIN",
	}
	AdminListUpdateType_value = map[string]int32{
		"ADMIN_LIST_UPDATE_TYPE_UNSPECIFIED":        0,
		"ADMIN_LIST_UPDATE_TYPE_ADD_ADMIN":          1,
		"ADMIN_LIST_UPDATE_TYPE_REMOVE_ADMIN":       2,
		"ADMIN_LIST_UPDATE_TYPE_ADD_SUPER_ADMIN":    3,
		"ADMIN_LIST_UPDATE_TYPE_REMOVE_SUPER_ADMIN": 4,
	}
)

func (x AdminListUpdateType) Enum() *AdminListUpdateType {
	p := new(AdminListUpdateType)
	*p = x
	return p
}

func (x AdminListUpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminListUpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_mls_database_intents_proto_enumTypes[0].Descriptor()
}

func (AdminListUpdateType) Type() protoreflect.EnumType {
	return &file_mls_database_intents_proto_enumTypes[0]
}

func (x AdminListUpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminListUpdateType.Descriptor instead.
func (AdminListUpdateType) EnumDescriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{0}
}

// Type of Permission to Update
type PermissionUpdateType int32

const (
	PermissionUpdateType_PERMISSION_UPDATE_TYPE_UNSPECIFIED     PermissionUpdateType = 0
	PermissionUpdateType_PERMISSION_UPDATE_TYPE_ADD_MEMBER      PermissionUpdateType = 1
	PermissionUpdateType_PERMISSION_UPDATE_TYPE_REMOVE_MEMBER   PermissionUpdateType = 2
	PermissionUpdateType_PERMISSION_UPDATE_TYPE_ADD_ADMIN       PermissionUpdateType = 3
	PermissionUpdateType_PERMISSION_UPDATE_TYPE_REMOVE_ADMIN    PermissionUpdateType = 4
	PermissionUpdateType_PERMISSION_UPDATE_TYPE_UPDATE_METADATA PermissionUpdateType = 5
)

// Enum value maps for PermissionUpdateType.
var (
	PermissionUpdateType_name = map[int32]string{
		0: "PERMISSION_UPDATE_TYPE_UNSPECIFIED",
		1: "PERMISSION_UPDATE_TYPE_ADD_MEMBER",
		2: "PERMISSION_UPDATE_TYPE_REMOVE_MEMBER",
		3: "PERMISSION_UPDATE_TYPE_ADD_ADMIN",
		4: "PERMISSION_UPDATE_TYPE_REMOVE_ADMIN",
		5: "PERMISSION_UPDATE_TYPE_UPDATE_METADATA",
	}
	PermissionUpdateType_value = map[string]int32{
		"PERMISSION_UPDATE_TYPE_UNSPECIFIED":     0,
		"PERMISSION_UPDATE_TYPE_ADD_MEMBER":      1,
		"PERMISSION_UPDATE_TYPE_REMOVE_MEMBER":   2,
		"PERMISSION_UPDATE_TYPE_ADD_ADMIN":       3,
		"PERMISSION_UPDATE_TYPE_REMOVE_ADMIN":    4,
		"PERMISSION_UPDATE_TYPE_UPDATE_METADATA": 5,
	}
)

func (x PermissionUpdateType) Enum() *PermissionUpdateType {
	p := new(PermissionUpdateType)
	*p = x
	return p
}

func (x PermissionUpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionUpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_mls_database_intents_proto_enumTypes[1].Descriptor()
}

func (PermissionUpdateType) Type() protoreflect.EnumType {
	return &file_mls_database_intents_proto_enumTypes[1]
}

func (x PermissionUpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionUpdateType.Descriptor instead.
func (PermissionUpdateType) EnumDescriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{1}
}

// Permission Policy
type PermissionPolicyOption int32

const (
	PermissionPolicyOption_PERMISSION_POLICY_OPTION_UNSPECIFIED      PermissionPolicyOption = 0
	PermissionPolicyOption_PERMISSION_POLICY_OPTION_ALLOW            PermissionPolicyOption = 1
	PermissionPolicyOption_PERMISSION_POLICY_OPTION_DENY             PermissionPolicyOption = 2
	PermissionPolicyOption_PERMISSION_POLICY_OPTION_ADMIN_ONLY       PermissionPolicyOption = 3
	PermissionPolicyOption_PERMISSION_POLICY_OPTION_SUPER_ADMIN_ONLY PermissionPolicyOption = 4
)

// Enum value maps for PermissionPolicyOption.
var (
	PermissionPolicyOption_name = map[int32]string{
		0: "PERMISSION_POLICY_OPTION_UNSPECIFIED",
		1: "PERMISSION_POLICY_OPTION_ALLOW",
		2: "PERMISSION_POLICY_OPTION_DENY",
		3: "PERMISSION_POLICY_OPTION_ADMIN_ONLY",
		4: "PERMISSION_POLICY_OPTION_SUPER_ADMIN_ONLY",
	}
	PermissionPolicyOption_value = map[string]int32{
		"PERMISSION_POLICY_OPTION_UNSPECIFIED":      0,
		"PERMISSION_POLICY_OPTION_ALLOW":            1,
		"PERMISSION_POLICY_OPTION_DENY":             2,
		"PERMISSION_POLICY_OPTION_ADMIN_ONLY":       3,
		"PERMISSION_POLICY_OPTION_SUPER_ADMIN_ONLY": 4,
	}
)

func (x PermissionPolicyOption) Enum() *PermissionPolicyOption {
	p := new(PermissionPolicyOption)
	*p = x
	return p
}

func (x PermissionPolicyOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionPolicyOption) Descriptor() protoreflect.EnumDescriptor {
	return file_mls_database_intents_proto_enumTypes[2].Descriptor()
}

func (PermissionPolicyOption) Type() protoreflect.EnumType {
	return &file_mls_database_intents_proto_enumTypes[2]
}

func (x PermissionPolicyOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionPolicyOption.Descriptor instead.
func (PermissionPolicyOption) EnumDescriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{2}
}

// The data required to publish a message
type SendMessageData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*SendMessageData_V1_
	Version       isSendMessageData_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageData) Reset() {
	*x = SendMessageData{}
	mi := &file_mls_database_intents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageData) ProtoMessage() {}

func (x *SendMessageData) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageData.ProtoReflect.Descriptor instead.
func (*SendMessageData) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageData) GetVersion() isSendMessageData_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *SendMessageData) GetV1() *SendMessageData_V1 {
	if x != nil {
		if x, ok := x.Version.(*SendMessageData_V1_); ok {
			return x.V1
		}
	}
	return nil
}

type isSendMessageData_Version interface {
	isSendMessageData_Version()
}

type SendMessageData_V1_ struct {
	V1 *SendMessageData_V1 `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*SendMessageData_V1_) isSendMessageData_Version() {}

// Wrapper around a list af repeated EVM Account Addresses
type AccountAddresses struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountAddresses []string               `protobuf:"bytes,1,rep,name=account_addresses,json=accountAddresses,proto3" json:"account_addresses,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountAddresses) Reset() {
	*x = AccountAddresses{}
	mi := &file_mls_database_intents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountAddresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountAddresses) ProtoMessage() {}

func (x *AccountAddresses) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountAddresses.ProtoReflect.Descriptor instead.
func (*AccountAddresses) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{1}
}

func (x *AccountAddresses) GetAccountAddresses() []string {
	if x != nil {
		return x.AccountAddresses
	}
	return nil
}

// Wrapper around a list of repeated Installation IDs
type InstallationIds struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstallationIds [][]byte               `protobuf:"bytes,1,rep,name=installation_ids,json=installationIds,proto3" json:"installation_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InstallationIds) Reset() {
	*x = InstallationIds{}
	mi := &file_mls_database_intents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallationIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallationIds) ProtoMessage() {}

func (x *InstallationIds) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallationIds.ProtoReflect.Descriptor instead.
func (*InstallationIds) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{2}
}

func (x *InstallationIds) GetInstallationIds() [][]byte {
	if x != nil {
		return x.InstallationIds
	}
	return nil
}

// One of an EVM account address or Installation ID
type AddressesOrInstallationIds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to AddressesOrInstallationIds:
	//
	//	*AddressesOrInstallationIds_AccountAddresses
	//	*AddressesOrInstallationIds_InstallationIds
	AddressesOrInstallationIds isAddressesOrInstallationIds_AddressesOrInstallationIds `protobuf_oneof:"addresses_or_installation_ids"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *AddressesOrInstallationIds) Reset() {
	*x = AddressesOrInstallationIds{}
	mi := &file_mls_database_intents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressesOrInstallationIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressesOrInstallationIds) ProtoMessage() {}

func (x *AddressesOrInstallationIds) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressesOrInstallationIds.ProtoReflect.Descriptor instead.
func (*AddressesOrInstallationIds) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{3}
}

func (x *AddressesOrInstallationIds) GetAddressesOrInstallationIds() isAddressesOrInstallationIds_AddressesOrInstallationIds {
	if x != nil {
		return x.AddressesOrInstallationIds
	}
	return nil
}

func (x *AddressesOrInstallationIds) GetAccountAddresses() *AccountAddresses {
	if x != nil {
		if x, ok := x.AddressesOrInstallationIds.(*AddressesOrInstallationIds_AccountAddresses); ok {
			return x.AccountAddresses
		}
	}
	return nil
}

func (x *AddressesOrInstallationIds) GetInstallationIds() *InstallationIds {
	if x != nil {
		if x, ok := x.AddressesOrInstallationIds.(*AddressesOrInstallationIds_InstallationIds); ok {
			return x.InstallationIds
		}
	}
	return nil
}

type isAddressesOrInstallationIds_AddressesOrInstallationIds interface {
	isAddressesOrInstallationIds_AddressesOrInstallationIds()
}

type AddressesOrInstallationIds_AccountAddresses struct {
	AccountAddresses *AccountAddresses `protobuf:"bytes,1,opt,name=account_addresses,json=accountAddresses,proto3,oneof"`
}

type AddressesOrInstallationIds_InstallationIds struct {
	InstallationIds *InstallationIds `protobuf:"bytes,2,opt,name=installation_ids,json=installationIds,proto3,oneof"`
}

func (*AddressesOrInstallationIds_AccountAddresses) isAddressesOrInstallationIds_AddressesOrInstallationIds() {
}

func (*AddressesOrInstallationIds_InstallationIds) isAddressesOrInstallationIds_AddressesOrInstallationIds() {
}

// The data required to add members to a group
type AddMembersData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*AddMembersData_V1_
	Version       isAddMembersData_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMembersData) Reset() {
	*x = AddMembersData{}
	mi := &file_mls_database_intents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMembersData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembersData) ProtoMessage() {}

func (x *AddMembersData) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembersData.ProtoReflect.Descriptor instead.
func (*AddMembersData) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{4}
}

func (x *AddMembersData) GetVersion() isAddMembersData_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *AddMembersData) GetV1() *AddMembersData_V1 {
	if x != nil {
		if x, ok := x.Version.(*AddMembersData_V1_); ok {
			return x.V1
		}
	}
	return nil
}

type isAddMembersData_Version interface {
	isAddMembersData_Version()
}

type AddMembersData_V1_ struct {
	V1 *AddMembersData_V1 `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*AddMembersData_V1_) isAddMembersData_Version() {}

// The data required to remove members from a group
type RemoveMembersData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*RemoveMembersData_V1_
	Version       isRemoveMembersData_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMembersData) Reset() {
	*x = RemoveMembersData{}
	mi := &file_mls_database_intents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMembersData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMembersData) ProtoMessage() {}

func (x *RemoveMembersData) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMembersData.ProtoReflect.Descriptor instead.
func (*RemoveMembersData) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveMembersData) GetVersion() isRemoveMembersData_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *RemoveMembersData) GetV1() *RemoveMembersData_V1 {
	if x != nil {
		if x, ok := x.Version.(*RemoveMembersData_V1_); ok {
			return x.V1
		}
	}
	return nil
}

type isRemoveMembersData_Version interface {
	isRemoveMembersData_Version()
}

type RemoveMembersData_V1_ struct {
	V1 *RemoveMembersData_V1 `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*RemoveMembersData_V1_) isRemoveMembersData_Version() {}

// The data required to make a commit that updates group membership
// Handles both Add and Remove actions
type UpdateGroupMembershipData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*UpdateGroupMembershipData_V1_
	Version       isUpdateGroupMembershipData_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupMembershipData) Reset() {
	*x = UpdateGroupMembershipData{}
	mi := &file_mls_database_intents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupMembershipData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupMembershipData) ProtoMessage() {}

func (x *UpdateGroupMembershipData) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupMembershipData.ProtoReflect.Descriptor instead.
func (*UpdateGroupMembershipData) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGroupMembershipData) GetVersion() isUpdateGroupMembershipData_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *UpdateGroupMembershipData) GetV1() *UpdateGroupMembershipData_V1 {
	if x != nil {
		if x, ok := x.Version.(*UpdateGroupMembershipData_V1_); ok {
			return x.V1
		}
	}
	return nil
}

type isUpdateGroupMembershipData_Version interface {
	isUpdateGroupMembershipData_Version()
}

type UpdateGroupMembershipData_V1_ struct {
	V1 *UpdateGroupMembershipData_V1 `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*UpdateGroupMembershipData_V1_) isUpdateGroupMembershipData_Version() {}

// The data required to update group metadata
type UpdateMetadataData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*UpdateMetadataData_V1_
	Version       isUpdateMetadataData_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataData) Reset() {
	*x = UpdateMetadataData{}
	mi := &file_mls_database_intents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataData) ProtoMessage() {}

func (x *UpdateMetadataData) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataData.ProtoReflect.Descriptor instead.
func (*UpdateMetadataData) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMetadataData) GetVersion() isUpdateMetadataData_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *UpdateMetadataData) GetV1() *UpdateMetadataData_V1 {
	if x != nil {
		if x, ok := x.Version.(*UpdateMetadataData_V1_); ok {
			return x.V1
		}
	}
	return nil
}

type isUpdateMetadataData_Version interface {
	isUpdateMetadataData_Version()
}

type UpdateMetadataData_V1_ struct {
	V1 *UpdateMetadataData_V1 `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*UpdateMetadataData_V1_) isUpdateMetadataData_Version() {}

// The data required to update group admin/super admin lists
type UpdateAdminListsData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*UpdateAdminListsData_V1_
	Version       isUpdateAdminListsData_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminListsData) Reset() {
	*x = UpdateAdminListsData{}
	mi := &file_mls_database_intents_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminListsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminListsData) ProtoMessage() {}

func (x *UpdateAdminListsData) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminListsData.ProtoReflect.Descriptor instead.
func (*UpdateAdminListsData) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAdminListsData) GetVersion() isUpdateAdminListsData_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *UpdateAdminListsData) GetV1() *UpdateAdminListsData_V1 {
	if x != nil {
		if x, ok := x.Version.(*UpdateAdminListsData_V1_); ok {
			return x.V1
		}
	}
	return nil
}

type isUpdateAdminListsData_Version interface {
	isUpdateAdminListsData_Version()
}

type UpdateAdminListsData_V1_ struct {
	V1 *UpdateAdminListsData_V1 `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*UpdateAdminListsData_V1_) isUpdateAdminListsData_Version() {}

// The data required to update permissions
type UpdatePermissionData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*UpdatePermissionData_V1_
	Version       isUpdatePermissionData_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionData) Reset() {
	*x = UpdatePermissionData{}
	mi := &file_mls_database_intents_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionData) ProtoMessage() {}

func (x *UpdatePermissionData) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionData.ProtoReflect.Descriptor instead.
func (*UpdatePermissionData) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePermissionData) GetVersion() isUpdatePermissionData_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *UpdatePermissionData) GetV1() *UpdatePermissionData_V1 {
	if x != nil {
		if x, ok := x.Version.(*UpdatePermissionData_V1_); ok {
			return x.V1
		}
	}
	return nil
}

type isUpdatePermissionData_Version interface {
	isUpdatePermissionData_Version()
}

type UpdatePermissionData_V1_ struct {
	V1 *UpdatePermissionData_V1 `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*UpdatePermissionData_V1_) isUpdatePermissionData_Version() {}

// Generic data-type for all post-commit actions
type PostCommitAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*PostCommitAction_SendWelcomes_
	Kind          isPostCommitAction_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCommitAction) Reset() {
	*x = PostCommitAction{}
	mi := &file_mls_database_intents_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommitAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommitAction) ProtoMessage() {}

func (x *PostCommitAction) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommitAction.ProtoReflect.Descriptor instead.
func (*PostCommitAction) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{10}
}

func (x *PostCommitAction) GetKind() isPostCommitAction_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *PostCommitAction) GetSendWelcomes() *PostCommitAction_SendWelcomes {
	if x != nil {
		if x, ok := x.Kind.(*PostCommitAction_SendWelcomes_); ok {
			return x.SendWelcomes
		}
	}
	return nil
}

type isPostCommitAction_Kind interface {
	isPostCommitAction_Kind()
}

type PostCommitAction_SendWelcomes_ struct {
	SendWelcomes *PostCommitAction_SendWelcomes `protobuf:"bytes,1,opt,name=send_welcomes,json=sendWelcomes,proto3,oneof"`
}

func (*PostCommitAction_SendWelcomes_) isPostCommitAction_Kind() {}

// V1 of SendMessagePublishData
type SendMessageData_V1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadBytes  []byte                 `protobuf:"bytes,1,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageData_V1) Reset() {
	*x = SendMessageData_V1{}
	mi := &file_mls_database_intents_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageData_V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageData_V1) ProtoMessage() {}

func (x *SendMessageData_V1) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageData_V1.ProtoReflect.Descriptor instead.
func (*SendMessageData_V1) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SendMessageData_V1) GetPayloadBytes() []byte {
	if x != nil {
		return x.PayloadBytes
	}
	return nil
}

// V1 of AddMembersPublishData
type AddMembersData_V1 struct {
	state                      protoimpl.MessageState      `protogen:"open.v1"`
	AddressesOrInstallationIds *AddressesOrInstallationIds `protobuf:"bytes,1,opt,name=addresses_or_installation_ids,json=addressesOrInstallationIds,proto3" json:"addresses_or_installation_ids,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *AddMembersData_V1) Reset() {
	*x = AddMembersData_V1{}
	mi := &file_mls_database_intents_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMembersData_V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembersData_V1) ProtoMessage() {}

func (x *AddMembersData_V1) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembersData_V1.ProtoReflect.Descriptor instead.
func (*AddMembersData_V1) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{4, 0}
}

func (x *AddMembersData_V1) GetAddressesOrInstallationIds() *AddressesOrInstallationIds {
	if x != nil {
		return x.AddressesOrInstallationIds
	}
	return nil
}

// V1 of RemoveMembersPublishData
type RemoveMembersData_V1 struct {
	state                      protoimpl.MessageState      `protogen:"open.v1"`
	AddressesOrInstallationIds *AddressesOrInstallationIds `protobuf:"bytes,1,opt,name=addresses_or_installation_ids,json=addressesOrInstallationIds,proto3" json:"addresses_or_installation_ids,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RemoveMembersData_V1) Reset() {
	*x = RemoveMembersData_V1{}
	mi := &file_mls_database_intents_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMembersData_V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMembersData_V1) ProtoMessage() {}

func (x *RemoveMembersData_V1) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMembersData_V1.ProtoReflect.Descriptor instead.
func (*RemoveMembersData_V1) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{5, 0}
}

func (x *RemoveMembersData_V1) GetAddressesOrInstallationIds() *AddressesOrInstallationIds {
	if x != nil {
		return x.AddressesOrInstallationIds
	}
	return nil
}

// V1 of UpdateGroupMembershipPublishData
type UpdateGroupMembershipData_V1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains delta of membership updates that need to be applied
	MembershipUpdates map[string]uint64 `protobuf:"bytes,1,rep,name=membership_updates,json=membershipUpdates,proto3" json:"membership_updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Contains the list of members that will be removed
	RemovedMembers []string `protobuf:"bytes,2,rep,name=removed_members,json=removedMembers,proto3" json:"removed_members,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateGroupMembershipData_V1) Reset() {
	*x = UpdateGroupMembershipData_V1{}
	mi := &file_mls_database_intents_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupMembershipData_V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupMembershipData_V1) ProtoMessage() {}

func (x *UpdateGroupMembershipData_V1) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupMembershipData_V1.ProtoReflect.Descriptor instead.
func (*UpdateGroupMembershipData_V1) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{6, 0}
}

func (x *UpdateGroupMembershipData_V1) GetMembershipUpdates() map[string]uint64 {
	if x != nil {
		return x.MembershipUpdates
	}
	return nil
}

func (x *UpdateGroupMembershipData_V1) GetRemovedMembers() []string {
	if x != nil {
		return x.RemovedMembers
	}
	return nil
}

// V1 of UpdateMetadataPublishData
type UpdateMetadataData_V1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldName     string                 `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldValue    string                 `protobuf:"bytes,2,opt,name=field_value,json=fieldValue,proto3" json:"field_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetadataData_V1) Reset() {
	*x = UpdateMetadataData_V1{}
	mi := &file_mls_database_intents_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetadataData_V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataData_V1) ProtoMessage() {}

func (x *UpdateMetadataData_V1) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataData_V1.ProtoReflect.Descriptor instead.
func (*UpdateMetadataData_V1) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{7, 0}
}

func (x *UpdateMetadataData_V1) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *UpdateMetadataData_V1) GetFieldValue() string {
	if x != nil {
		return x.FieldValue
	}
	return ""
}

// V1 of UpdateAdminListsPublishData
type UpdateAdminListsData_V1 struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AdminListUpdateType AdminListUpdateType    `protobuf:"varint,1,opt,name=admin_list_update_type,json=adminListUpdateType,proto3,enum=xmtp.mls.database.AdminListUpdateType" json:"admin_list_update_type,omitempty"`
	InboxId             string                 `protobuf:"bytes,2,opt,name=inbox_id,json=inboxId,proto3" json:"inbox_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateAdminListsData_V1) Reset() {
	*x = UpdateAdminListsData_V1{}
	mi := &file_mls_database_intents_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminListsData_V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminListsData_V1) ProtoMessage() {}

func (x *UpdateAdminListsData_V1) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminListsData_V1.ProtoReflect.Descriptor instead.
func (*UpdateAdminListsData_V1) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{8, 0}
}

func (x *UpdateAdminListsData_V1) GetAdminListUpdateType() AdminListUpdateType {
	if x != nil {
		return x.AdminListUpdateType
	}
	return AdminListUpdateType_ADMIN_LIST_UPDATE_TYPE_UNSPECIFIED
}

func (x *UpdateAdminListsData_V1) GetInboxId() string {
	if x != nil {
		return x.InboxId
	}
	return ""
}

// V1 of UpdatePermissionData
type UpdatePermissionData_V1 struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PermissionUpdateType   PermissionUpdateType   `protobuf:"varint,1,opt,name=permission_update_type,json=permissionUpdateType,proto3,enum=xmtp.mls.database.PermissionUpdateType" json:"permission_update_type,omitempty"`
	PermissionPolicyOption PermissionPolicyOption `protobuf:"varint,2,opt,name=permission_policy_option,json=permissionPolicyOption,proto3,enum=xmtp.mls.database.PermissionPolicyOption" json:"permission_policy_option,omitempty"`
	// Metadata permissions update specify which field permission they are updating
	MetadataFieldName *string `protobuf:"bytes,3,opt,name=metadata_field_name,json=metadataFieldName,proto3,oneof" json:"metadata_field_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdatePermissionData_V1) Reset() {
	*x = UpdatePermissionData_V1{}
	mi := &file_mls_database_intents_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionData_V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionData_V1) ProtoMessage() {}

func (x *UpdatePermissionData_V1) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionData_V1.ProtoReflect.Descriptor instead.
func (*UpdatePermissionData_V1) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UpdatePermissionData_V1) GetPermissionUpdateType() PermissionUpdateType {
	if x != nil {
		return x.PermissionUpdateType
	}
	return PermissionUpdateType_PERMISSION_UPDATE_TYPE_UNSPECIFIED
}

func (x *UpdatePermissionData_V1) GetPermissionPolicyOption() PermissionPolicyOption {
	if x != nil {
		return x.PermissionPolicyOption
	}
	return PermissionPolicyOption_PERMISSION_POLICY_OPTION_UNSPECIFIED
}

func (x *UpdatePermissionData_V1) GetMetadataFieldName() string {
	if x != nil && x.MetadataFieldName != nil {
		return *x.MetadataFieldName
	}
	return ""
}

// An installation
type PostCommitAction_Installation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstallationKey []byte                 `protobuf:"bytes,1,opt,name=installation_key,json=installationKey,proto3" json:"installation_key,omitempty"`
	HpkePublicKey   []byte                 `protobuf:"bytes,2,opt,name=hpke_public_key,json=hpkePublicKey,proto3" json:"hpke_public_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PostCommitAction_Installation) Reset() {
	*x = PostCommitAction_Installation{}
	mi := &file_mls_database_intents_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommitAction_Installation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommitAction_Installation) ProtoMessage() {}

func (x *PostCommitAction_Installation) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommitAction_Installation.ProtoReflect.Descriptor instead.
func (*PostCommitAction_Installation) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{10, 0}
}

func (x *PostCommitAction_Installation) GetInstallationKey() []byte {
	if x != nil {
		return x.InstallationKey
	}
	return nil
}

func (x *PostCommitAction_Installation) GetHpkePublicKey() []byte {
	if x != nil {
		return x.HpkePublicKey
	}
	return nil
}

// SendWelcome message
type PostCommitAction_SendWelcomes struct {
	state          protoimpl.MessageState           `protogen:"open.v1"`
	Installations  []*PostCommitAction_Installation `protobuf:"bytes,1,rep,name=installations,proto3" json:"installations,omitempty"`
	WelcomeMessage []byte                           `protobuf:"bytes,2,opt,name=welcome_message,json=welcomeMessage,proto3" json:"welcome_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostCommitAction_SendWelcomes) Reset() {
	*x = PostCommitAction_SendWelcomes{}
	mi := &file_mls_database_intents_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCommitAction_SendWelcomes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCommitAction_SendWelcomes) ProtoMessage() {}

func (x *PostCommitAction_SendWelcomes) ProtoReflect() protoreflect.Message {
	mi := &file_mls_database_intents_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCommitAction_SendWelcomes.ProtoReflect.Descriptor instead.
func (*PostCommitAction_SendWelcomes) Descriptor() ([]byte, []int) {
	return file_mls_database_intents_proto_rawDescGZIP(), []int{10, 1}
}

func (x *PostCommitAction_SendWelcomes) GetInstallations() []*PostCommitAction_Installation {
	if x != nil {
		return x.Installations
	}
	return nil
}

func (x *PostCommitAction_SendWelcomes) GetWelcomeMessage() []byte {
	if x != nil {
		return x.WelcomeMessage
	}
	return nil
}

var File_mls_database_intents_proto protoreflect.FileDescriptor

var file_mls_database_intents_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x6c, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x78, 0x6d,
	0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x22,
	0x80, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x02, 0x76, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x56, 0x31, 0x48, 0x00, 0x52, 0x02, 0x76, 0x31, 0x1a, 0x29, 0x0a, 0x02,
	0x56, 0x31, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x3f, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x0f, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x0f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x73, 0x22, 0xe2, 0x01, 0x0a, 0x1a, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x4f,
	0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73,
	0x12, 0x52, 0x0a, 0x11, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x78, 0x6d,
	0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x48, 0x00, 0x52, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x65, 0x73, 0x12, 0x4f, 0x0a, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x73, 0x48, 0x00, 0x52, 0x0f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x73, 0x42, 0x1f, 0x0a, 0x1d, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x5f, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x22, 0xcb, 0x01, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x02, 0x76, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x56, 0x31, 0x48, 0x00, 0x52, 0x02, 0x76,
	0x31, 0x1a, 0x76, 0x0a, 0x02, 0x56, 0x31, 0x12, 0x70, 0x0a, 0x1d, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x65, 0x73, 0x5f, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d,
	0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x4f, 0x72, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x52, 0x1a, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x4f, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0xd1, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x39, 0x0a, 0x02, 0x76, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x6c,
	0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x56, 0x31, 0x48,
	0x00, 0x52, 0x02, 0x76, 0x31, 0x1a, 0x76, 0x0a, 0x02, 0x56, 0x31, 0x12, 0x70, 0x0a, 0x1d, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x5f, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x4f, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x73, 0x52, 0x1a, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x4f, 0x72, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x42, 0x09, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xd6, 0x02, 0x0a, 0x19, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x41, 0x0a, 0x02, 0x76, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x56, 0x31, 0x48, 0x00, 0x52, 0x02, 0x76, 0x31, 0x1a, 0xea, 0x01, 0x0a, 0x02, 0x56, 0x31,
	0x12, 0x75, 0x0a, 0x12, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x46, 0x2e, 0x78,
	0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x56, 0x31, 0x2e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x11, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x64, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0e, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x1a, 0x44, 0x0a, 0x16, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0xa1, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3a, 0x0a, 0x02, 0x76, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x56, 0x31, 0x48, 0x00,
	0x52, 0x02, 0x76, 0x31, 0x1a, 0x44, 0x0a, 0x02, 0x56, 0x31, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xdd, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3c,
	0x0a, 0x02, 0x76, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x78, 0x6d, 0x74,
	0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x73, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x56, 0x31, 0x48, 0x00, 0x52, 0x02, 0x76, 0x31, 0x1a, 0x7c, 0x0a, 0x02,
	0x56, 0x31, 0x12, 0x5b, 0x0a, 0x16, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x26, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x13, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xf7, 0x02, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3c,
	0x0a, 0x02, 0x76, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x78, 0x6d, 0x74,
	0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x56, 0x31, 0x48, 0x00, 0x52, 0x02, 0x76, 0x31, 0x1a, 0x95, 0x02, 0x0a,
	0x02, 0x56, 0x31, 0x12, 0x5d, 0x0a, 0x16, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x14, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x63, 0x0a, 0x18, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x16, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x13, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x11, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x16, 0x0a, 0x14,
	0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0xe8, 0x02, 0x0a, 0x10, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x57, 0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x77, 0x65, 0x6c,
	0x63, 0x6f, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x78, 0x6d,
	0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x73, 0x48, 0x00, 0x52,
	0x0c, 0x73, 0x65, 0x6e, 0x64, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x73, 0x1a, 0x61, 0x0a,
	0x0c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a,
	0x10, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x0f, 0x68, 0x70, 0x6b, 0x65,
	0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0d, 0x68, 0x70, 0x6b, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x1a, 0x8f, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65,
	0x73, 0x12, 0x56, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e,
	0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x50, 0x6f, 0x73,
	0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x77, 0x65, 0x6c,
	0x63, 0x6f, 0x6d, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0e, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x2a, 0xe7, 0x01, 0x0a, 0x13, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x26, 0x0a, 0x22, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x4c, 0x49, 0x53, 0x54,
	0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x24, 0x0a, 0x20, 0x41, 0x44,
	0x4d, 0x49, 0x4e, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x44, 0x44, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x01,
	0x12, 0x27, 0x0a, 0x23, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x55,
	0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56,
	0x45, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x02, 0x12, 0x2a, 0x0a, 0x26, 0x41, 0x44, 0x4d,
	0x49, 0x4e, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x41, 0x44, 0x44, 0x5f, 0x53, 0x55, 0x50, 0x45, 0x52, 0x5f, 0x41, 0x44,
	0x4d, 0x49, 0x4e, 0x10, 0x03, 0x12, 0x2d, 0x0a, 0x29, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x4c,
	0x49, 0x53, 0x54, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x53, 0x55, 0x50, 0x45, 0x52, 0x5f, 0x41, 0x44, 0x4d,
	0x49, 0x4e, 0x10, 0x04, 0x2a, 0x8a, 0x02, 0x0a, 0x14, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a,
	0x22, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x44, 0x41,
	0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x25, 0x0a, 0x21, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53,
	0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x41, 0x44, 0x44, 0x5f, 0x4d, 0x45, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x01, 0x12, 0x28, 0x0a, 0x24,
	0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x4d, 0x45,
	0x4d, 0x42, 0x45, 0x52, 0x10, 0x02, 0x12, 0x24, 0x0a, 0x20, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53,
	0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x41, 0x44, 0x44, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x03, 0x12, 0x27, 0x0a, 0x23,
	0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x41, 0x44,
	0x4d, 0x49, 0x4e, 0x10, 0x04, 0x12, 0x2a, 0x0a, 0x26, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53,
	0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x4d, 0x45, 0x54, 0x41, 0x44, 0x41, 0x54, 0x41, 0x10,
	0x05, 0x2a, 0xe1, 0x01, 0x0a, 0x16, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x24,
	0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x4f, 0x4c, 0x49, 0x43,
	0x59, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x22, 0x0a, 0x1e, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53,
	0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59, 0x5f, 0x4f, 0x50, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x01, 0x12, 0x21, 0x0a, 0x1d, 0x50, 0x45,
	0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59, 0x5f,
	0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x02, 0x12, 0x27, 0x0a,
	0x23, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x4f, 0x4c, 0x49,
	0x43, 0x59, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f,
	0x4f, 0x4e, 0x4c, 0x59, 0x10, 0x03, 0x12, 0x2d, 0x0a, 0x29, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53,
	0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59, 0x5f, 0x4f, 0x50, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x53, 0x55, 0x50, 0x45, 0x52, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x4f,
	0x4e, 0x4c, 0x59, 0x10, 0x04, 0x42, 0xb9, 0x01, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x78, 0x6d,
	0x74, 0x70, 0x2e, 0x6d, 0x6c, 0x73, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x42,
	0x0c, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x6d, 0x74, 0x70,
	0x2f, 0x78, 0x6d, 0x74, 0x70, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6d, 0x6c, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0xa2, 0x02, 0x03,
	0x58, 0x4d, 0x44, 0xaa, 0x02, 0x11, 0x58, 0x6d, 0x74, 0x70, 0x2e, 0x4d, 0x6c, 0x73, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0xca, 0x02, 0x11, 0x58, 0x6d, 0x74, 0x70, 0x5c, 0x4d,
	0x6c, 0x73, 0x5c, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0xe2, 0x02, 0x1d, 0x58, 0x6d,
	0x74, 0x70, 0x5c, 0x4d, 0x6c, 0x73, 0x5c, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x13, 0x58, 0x6d,
	0x74, 0x70, 0x3a, 0x3a, 0x4d, 0x6c, 0x73, 0x3a, 0x3a, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mls_database_intents_proto_rawDescOnce sync.Once
	file_mls_database_intents_proto_rawDescData = file_mls_database_intents_proto_rawDesc
)

func file_mls_database_intents_proto_rawDescGZIP() []byte {
	file_mls_database_intents_proto_rawDescOnce.Do(func() {
		file_mls_database_intents_proto_rawDescData = protoimpl.X.CompressGZIP(file_mls_database_intents_proto_rawDescData)
	})
	return file_mls_database_intents_proto_rawDescData
}

var file_mls_database_intents_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_mls_database_intents_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_mls_database_intents_proto_goTypes = []any{
	(AdminListUpdateType)(0),              // 0: xmtp.mls.database.AdminListUpdateType
	(PermissionUpdateType)(0),             // 1: xmtp.mls.database.PermissionUpdateType
	(PermissionPolicyOption)(0),           // 2: xmtp.mls.database.PermissionPolicyOption
	(*SendMessageData)(nil),               // 3: xmtp.mls.database.SendMessageData
	(*AccountAddresses)(nil),              // 4: xmtp.mls.database.AccountAddresses
	(*InstallationIds)(nil),               // 5: xmtp.mls.database.InstallationIds
	(*AddressesOrInstallationIds)(nil),    // 6: xmtp.mls.database.AddressesOrInstallationIds
	(*AddMembersData)(nil),                // 7: xmtp.mls.database.AddMembersData
	(*RemoveMembersData)(nil),             // 8: xmtp.mls.database.RemoveMembersData
	(*UpdateGroupMembershipData)(nil),     // 9: xmtp.mls.database.UpdateGroupMembershipData
	(*UpdateMetadataData)(nil),            // 10: xmtp.mls.database.UpdateMetadataData
	(*UpdateAdminListsData)(nil),          // 11: xmtp.mls.database.UpdateAdminListsData
	(*UpdatePermissionData)(nil),          // 12: xmtp.mls.database.UpdatePermissionData
	(*PostCommitAction)(nil),              // 13: xmtp.mls.database.PostCommitAction
	(*SendMessageData_V1)(nil),            // 14: xmtp.mls.database.SendMessageData.V1
	(*AddMembersData_V1)(nil),             // 15: xmtp.mls.database.AddMembersData.V1
	(*RemoveMembersData_V1)(nil),          // 16: xmtp.mls.database.RemoveMembersData.V1
	(*UpdateGroupMembershipData_V1)(nil),  // 17: xmtp.mls.database.UpdateGroupMembershipData.V1
	nil,                                   // 18: xmtp.mls.database.UpdateGroupMembershipData.V1.MembershipUpdatesEntry
	(*UpdateMetadataData_V1)(nil),         // 19: xmtp.mls.database.UpdateMetadataData.V1
	(*UpdateAdminListsData_V1)(nil),       // 20: xmtp.mls.database.UpdateAdminListsData.V1
	(*UpdatePermissionData_V1)(nil),       // 21: xmtp.mls.database.UpdatePermissionData.V1
	(*PostCommitAction_Installation)(nil), // 22: xmtp.mls.database.PostCommitAction.Installation
	(*PostCommitAction_SendWelcomes)(nil), // 23: xmtp.mls.database.PostCommitAction.SendWelcomes
}
var file_mls_database_intents_proto_depIdxs = []int32{
	14, // 0: xmtp.mls.database.SendMessageData.v1:type_name -> xmtp.mls.database.SendMessageData.V1
	4,  // 1: xmtp.mls.database.AddressesOrInstallationIds.account_addresses:type_name -> xmtp.mls.database.AccountAddresses
	5,  // 2: xmtp.mls.database.AddressesOrInstallationIds.installation_ids:type_name -> xmtp.mls.database.InstallationIds
	15, // 3: xmtp.mls.database.AddMembersData.v1:type_name -> xmtp.mls.database.AddMembersData.V1
	16, // 4: xmtp.mls.database.RemoveMembersData.v1:type_name -> xmtp.mls.database.RemoveMembersData.V1
	17, // 5: xmtp.mls.database.UpdateGroupMembershipData.v1:type_name -> xmtp.mls.database.UpdateGroupMembershipData.V1
	19, // 6: xmtp.mls.database.UpdateMetadataData.v1:type_name -> xmtp.mls.database.UpdateMetadataData.V1
	20, // 7: xmtp.mls.database.UpdateAdminListsData.v1:type_name -> xmtp.mls.database.UpdateAdminListsData.V1
	21, // 8: xmtp.mls.database.UpdatePermissionData.v1:type_name -> xmtp.mls.database.UpdatePermissionData.V1
	23, // 9: xmtp.mls.database.PostCommitAction.send_welcomes:type_name -> xmtp.mls.database.PostCommitAction.SendWelcomes
	6,  // 10: xmtp.mls.database.AddMembersData.V1.addresses_or_installation_ids:type_name -> xmtp.mls.database.AddressesOrInstallationIds
	6,  // 11: xmtp.mls.database.RemoveMembersData.V1.addresses_or_installation_ids:type_name -> xmtp.mls.database.AddressesOrInstallationIds
	18, // 12: xmtp.mls.database.UpdateGroupMembershipData.V1.membership_updates:type_name -> xmtp.mls.database.UpdateGroupMembershipData.V1.MembershipUpdatesEntry
	0,  // 13: xmtp.mls.database.UpdateAdminListsData.V1.admin_list_update_type:type_name -> xmtp.mls.database.AdminListUpdateType
	1,  // 14: xmtp.mls.database.UpdatePermissionData.V1.permission_update_type:type_name -> xmtp.mls.database.PermissionUpdateType
	2,  // 15: xmtp.mls.database.UpdatePermissionData.V1.permission_policy_option:type_name -> xmtp.mls.database.PermissionPolicyOption
	22, // 16: xmtp.mls.database.PostCommitAction.SendWelcomes.installations:type_name -> xmtp.mls.database.PostCommitAction.Installation
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_mls_database_intents_proto_init() }
func file_mls_database_intents_proto_init() {
	if File_mls_database_intents_proto != nil {
		return
	}
	file_mls_database_intents_proto_msgTypes[0].OneofWrappers = []any{
		(*SendMessageData_V1_)(nil),
	}
	file_mls_database_intents_proto_msgTypes[3].OneofWrappers = []any{
		(*AddressesOrInstallationIds_AccountAddresses)(nil),
		(*AddressesOrInstallationIds_InstallationIds)(nil),
	}
	file_mls_database_intents_proto_msgTypes[4].OneofWrappers = []any{
		(*AddMembersData_V1_)(nil),
	}
	file_mls_database_intents_proto_msgTypes[5].OneofWrappers = []any{
		(*RemoveMembersData_V1_)(nil),
	}
	file_mls_database_intents_proto_msgTypes[6].OneofWrappers = []any{
		(*UpdateGroupMembershipData_V1_)(nil),
	}
	file_mls_database_intents_proto_msgTypes[7].OneofWrappers = []any{
		(*UpdateMetadataData_V1_)(nil),
	}
	file_mls_database_intents_proto_msgTypes[8].OneofWrappers = []any{
		(*UpdateAdminListsData_V1_)(nil),
	}
	file_mls_database_intents_proto_msgTypes[9].OneofWrappers = []any{
		(*UpdatePermissionData_V1_)(nil),
	}
	file_mls_database_intents_proto_msgTypes[10].OneofWrappers = []any{
		(*PostCommitAction_SendWelcomes_)(nil),
	}
	file_mls_database_intents_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mls_database_intents_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mls_database_intents_proto_goTypes,
		DependencyIndexes: file_mls_database_intents_proto_depIdxs,
		EnumInfos:         file_mls_database_intents_proto_enumTypes,
		MessageInfos:      file_mls_database_intents_proto_msgTypes,
	}.Build()
	File_mls_database_intents_proto = out.File
	file_mls_database_intents_proto_rawDesc = nil
	file_mls_database_intents_proto_goTypes = nil
	file_mls_database_intents_proto_depIdxs = nil
}
