version: "2"
linters:
  default: none
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - nilerr
    - nakedret

formatters:
  enable:
    - gofmt
    - golines
    - gofumpt