version: "2"
linters:
  default: none
  enable:
    # Tier 1: Bug detection (already enabled)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - nilerr
    - nakedret
    - modernize
    # Tier 2: Autofix linters (new)
    - testifylint
    - perfsprint
    - intrange
    - copyloopvar
    - misspell
    - errorlint
    - protogetter
  exclusions:
    generated: lax

formatters:
  enable:
    - gofmt
    - golines
    - gofumpt
  exclusions:
    generated: lax
