with-expecter: True
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
dir: "pkg/mocks/{{.PackageName}}"
filename: "mock_{{.InterfaceName}}.go"
packages:
  github.com/xmtp/xmtpd/pkg/proto/xmtpv4/metadata_api:
    interfaces:
      MetadataApiClient:
  github.com/xmtp/xmtpd/pkg/authn:
    interfaces:
      JWTVerifier:
  github.com/xmtp/xmtpd/pkg/fees:
    interfaces:
      RatesContract:
  github.com/xmtp/xmtpd/pkg/mlsvalidate:
    interfaces:
      MLSValidationService:
  github.com/xmtp/xmtpd/pkg/proto/mls_validation/v1:
    interfaces:
      ValidationApiClient:
  github.com/xmtp/xmtpd/pkg/registry:
    interfaces:
      NodeRegistry:
      NodeRegistryContract:
  github.com/xmtp/xmtpd/pkg/indexer:
    interfaces:
      IBlockTracker:
      ChainReorgHandler:
  github.com/xmtp/xmtpd/pkg/blockchain:
    interfaces:
      ChainClient:
      IBlockchainPublisher:
      NonceManager:
  github.com/xmtp/xmtpd/pkg/indexer/storer:
    interfaces:
      LogStorer:
