with-expecter: True
testonly: True
dir: pkg/mocks
mockname: "Mock{{.InterfaceName}}"
outpkg: mocks
filename: "mock_{{.InterfaceName}}.go"
packages:
  github.com/xmtp/xmtpd/pkg/indexer/blockchain:
    interfaces:
      ChainClient:
  github.com/xmtp/xmtpd/pkg/indexer/storer:
    interfaces:
      LogStorer:
