        go get github.com/uptrace/bun/migrate
        go get google.golang.org/protobuf/reflect/protoreflect
        go get google.golang.org/protobuf/runtime/protoimpl
        go get github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options
        go get github.com/grpc-ecosystem/grpc-gateway/v2/runtime
        go get github.com/grpc-ecosystem/grpc-gateway/v2/utilities
        go get google.golang.org/genproto/googleapis/api/annotations
        go get google.golang.org/grpc
        go get google.golang.org/grpc/codes
        go get google.golang.org/grpc/grpclog
        go get google.golang.org/grpc/metadata
        go get google.golang.org/grpc/status
        go get google.golang.org/protobuf/proto
        go get google.golang.org/protobuf/types/known/emptypb
        go get github.com/ethereum/go-ethereum/crypto
        go get github.com/uptrace/bun
        go get github.com/uptrace/bun/dialect/pgdialect
        go get github.com/xmtp/xmtpd/pkg/migrations/replication
        go get github.com/xmtp/xmtpd/pkg/replication/api
        go get github.com/xmtp/xmtpd/pkg/replication/registry
        go get github.com/xmtp/xmtpd/pkg/server
        go get go.uber.org/zap
        go get github.com/pires/go-proxyproto
        go get github.com/xmtp/xmtpd/pkg/proto/xmtpv4/message_api
        go get github.com/xmtp/xmtpd/pkg/tracing
        go get google.golang.org/grpc/credentials/insecure
        go get google.golang.org/grpc/health
        go get google.golang.org/grpc/health/grpc_health_v1
        go get google.golang.org/grpc/keepalive
        go get github.com/jessevdk/go-flags
        go get github.com/xmtp/xmtpd/pkg/replication
        go get go.uber.org/zap/zapcore