#!/bin/bash
set -eou pipefail

go mod download

COMMIT=$(git rev-parse --short HEAD)
LD_FLAGS="-X 'main.GitCommit=${COMMIT}'"

pids=()
for dir in ./cmd/*; do
    if [ -d "$dir" ]; then
        go build -ldflags="${LD_FLAGS}" -o "./bin/${dir##*/}" "${dir}" &
        pids+=("$!")
    fi
done

for pid in ${pids[@]+"${pids[@]}"}; do
    wait "${pid}"
done
