#!/usr/bin/env bash

rm -rf pkg/proto/**/*.pb.go pkg/proto/**/*.pb.gw.go pkg/proto/**/*.swagger.json
if ! go tool -modfile=tools/go.mod buf generate https://github.com/xmtp/proto.git#subdir=proto,branch=mkysel/addtargettopayer; then
    echo "Failed to generate protobuf definitions"
    exit 1
fi