#!/usr/bin/env bash

rm -rf pkg/proto/**/*.pb.go pkg/proto/**/*.pb.gw.go pkg/proto/**/*.swagger.json
if ! buf generate https://github.com/xmtp/proto.git#subdir=proto,ref=08c80536d56e73c6f585d80e7cd2de3db6733c8b; then
    echo "Failed to generate protobuf definitions"
    exit 1
fi