#!/usr/bin/env bash

rm -rf pkg/proto/**/*.pb.go pkg/proto/**/*.pb.gw.go pkg/proto/**/*.swagger.json
if ! buf generate https://github.com/xmtp/proto.git#subdir=proto,branch=rich/simplify-batch-queries; then
    echo "Failed to generate protobuf definitions"
    exit 1
fi