#!/usr/bin/env bash

rm -rf pkg/proto/**/*.pb.go pkg/proto/**/*.pb.gw.go pkg/proto/**/*.swagger.json
if ! buf generate https://github.com/xmtp/proto.git#subdir=proto,branch=rich/add-identity-update-to-client-env; then
    echo "Failed to generate protobuf definitions"
    exit 1
fi