#!/usr/bin/env sh
set -e

go generate ./...
mockery

rm -rf pkg/proto/**/*.pb.go pkg/proto/**/*.pb.gw.go pkg/proto/**/*.swagger.json
if ! buf generate https://github.com/xmtp/proto.git#subdir=proto; then
    echo "Failed to generate protobuf definitions"
    exit 1
fi