#!/usr/bin/env bash

set -euo pipefail

rm -rf pkg/proto/**/*.pb.go pkg/proto/**/*.pb.gw.go pkg/proto/**/*.swagger.json
if ! buf generate https://github.com/xmtp/proto.git#subdir=proto,branch=nm/add-get-inbox-ids; then
    echo "Failed to generate protobuf definitions"
    exit 1
fi

go generate ./...
rm -rf pkg/mocks/*
./dev/abigen
mockery
sqlc generate