#!/bin/bash
set -eou pipefail

dev/lint-shellcheck

dev/lint-markdown

dev/terraform/lint

if [[ $(gofmt -l .) ]]; then
    echo "gofmt errors, run 'dev/fmt' and commit"
    exit 1
fi 

golangci-lint run ./...
