#!/bin/bash

set -eu

. dev/local.env

dev/cli register-node \
    --http-address=http://localhost:5051 \
    --owner-address=0xf0490b45884803924Ca84C2051ef435991D7350D \
    --admin-private-key=$PRIVATE_KEY \
    --signing-key-pub=0x03da7f733d870237f6dfd0074aea27edaf7b840d68e88641fb2a687de16bbe6a2b