#!/bin/bash

set -eu

. dev/local.env

export NODE_ADDRESS=$ANVIL_ACC_1_ADDRESS

dev/cli register-node \
    --http-address=http://localhost:5050 \
    --owner-address=$NODE_ADDRESS \
    --admin-private-key=$PRIVATE_KEY \
    --signing-key-pub=$XMTPD_SIGNER_PUBLIC_KEY