#!/bin/bash

set -eu

. dev/local.env

export XMTPD_REFLECTION_ENABLE=true
export XMTPD_API_ENABLE=true
export XMTPD_SYNC_ENABLE=true
export XMTPD_INDEXER_ENABLE=true
export XMTPD_METRICS_ENABLE=true
export XMTPD_METRICS_METRICS_ADDRESS=0.0.0.0
export XMTPD_CONTRACTS_ENVIRONMENT=anvil

go run -ldflags="-X main.Version=$(git describe HEAD --tags --long)" cmd/replication/main.go "$@"
