#!/bin/bash

set -eu

. dev/local.env

export XMTPD_REFLECTION_ENABLE=true
export XMTPD_REPLICATION_ENABLE=true
export XMTPD_SYNC_ENABLE=true
export XMTPD_INDEXER_ENABLE=true
export XMTPD_METRICS_ENABLE=true
export XMTPD_METRICS_METRICS_ADDRESS=0.0.0.0
export XMTPD_CONTRACTS_CONFIG_FILE_PATH=./dev/environments/anvil.json

go run -ldflags="-X main.Version=$(git describe HEAD --tags --long)" cmd/replication/main.go "$@"