#!/bin/bash

set -eu

. dev/local.env

export XMTPD_SIGNER_PRIVATE_KEY=$ANVIL_ACC_2_PRIVATE_KEY
export XMTPD_PAYER_PRIVATE_KEY=$XMTPD_SIGNER_PRIVATE_KEY
export XMTPD_DB_WRITER_CONNECTION_STRING="postgres://postgres:xmtp@localhost:8766/postgres?sslmode=disable"

export XMTPD_REFLECTION_ENABLE=true
export XMTPD_PAYER_ENABLE=true
export XMTPD_REPLICATION_ENABLE=true
export XMTPD_SYNC_ENABLE=true
export XMTPD_INDEXER_ENABLE=true
export XMTPD_CONTRACTS_CONFIG_FILE_PATH=./dev/environments/anvil.json

go run -ldflags="-X main.Version=$(git describe HEAD --tags --long)" cmd/replication/main.go -p 5051 --api.http-port 5056 "$@"
