#!/bin/bash

set -eu

. dev/local.env

export XMTPD_REFLECTION_ENABLE=true
export XMTPD_CONTRACTS_ENVIRONMENT=anvil
export XMTPD_API_PORT="5152"

go run -ldflags="-X main.Version=$(git describe HEAD --tags --long)" cmd/gateway/main.go "$@"
