#!/bin/bash

set -eu

. dev/local.env

export XMTPD_PAYER_REPORT_RUN_WORKERS=true
export XMTPD_CONTRACTS_ENVIRONMENT=anvil

go run -ldflags="-X main.Version=$(git describe HEAD --tags --long)" cmd/replication/main.go "$@"
