#!/bin/bash
set -eou pipefail
set -a; source .env.local; set +a

PORT="${PORT:-5001}"

dev/run \
    start \
    --p2p.port=9000 \
    --api.grpc-port=5000 \
    --api.http-port="${PORT}" \
    --store.type=postgres \
    "$@"
