#!/bin/bash
set -eo pipefail
set -a; source .env.local; set +a

PORT="${PORT:-5000}"
GIT_COMMIT="$(git rev-parse HEAD)"

go run \
    -ldflags="-X 'main.GitCommit=${GIT_COMMIT}'" \
    cmd/xmtpd/main.go \
    --p2p.port=9000 \
    --api.grpc-port=5000 \
    --api.http-port=5001 \
    "$@"
