#!/bin/bash
set -eo pipefail
set -a; source .env.local; set +a

PORT="${PORT:-5000}"
GIT_COMMIT="$(git rev-parse HEAD)"

go run \
    -ldflags="-X 'main.GitCommit=${GIT_COMMIT}'" \
    cmd/xmtpd/main.go \
    --store.type=postgres \
    "$@"
