#!/bin/bash
set -e

ulimit -n 2048

go test -timeout 10s `go list ./... | grep -v -e 'pkg/abis' -e 'pkg/config' -e 'pkg/proto' -e 'pkg/mock' -e 'pkg/testing'` "$@"

if [ -n "${RACE:-}" ]; then
    echo
    echo "Running race tests"
    go test ./... "$@" -race
fi
