#!/bin/bash
set -e

# Work always from the root directory
script_dir=$(dirname "$(realpath "$0")")
repo_root=$(realpath "${script_dir}/../")
cd "${repo_root}"

if ! which shellcheck &>/dev/null; then brew install shellcheck; fi
if ! which jq &>/dev/null; then brew install jq; fi
if ! which golangci-lint; then brew install golangci-lint; fi

#
# Usage: dev/up <profile>
#
# Profile values:
# - single: 1 node
# - dual: 2 nodes
# - default case: single
#

echo -e "→ Update Go dependencies"
go mod tidy

echo -e "→ Start docker containers"
dev/docker/up "${@}"

echo -e "→ Generating .env"
dev/gen/env
