#!/bin/bash
set -eo pipefail

if [[ "${OSTYPE}" == "darwin"* ]]; then
    if ! which golangci-lint &>/dev/null; then brew install golangci-lint; fi
    if ! which shellcheck &>/dev/null; then brew install shellcheck; fi
    if ! which markdownlint &>/dev/null; then brew install markdownlint-cli; fi
    if ! which staticcheck &>/dev/null; then brew install staticcheck; fi
fi

if ! which mockgen &>/dev/null; then go install github.com/golang/mock/mockgen@v1.6.0; fi

go mod tidy

dev/generate
