#!/bin/bash
# Deploy the smart contracts to the local anvil node
set -euo pipefail

# Make sure the build directory exists
mkdir -p ./build

# Always work from the contracts directory
script_dir=$(dirname "$(realpath "$0")")
repo_root=$(realpath "${script_dir}/../")
cd "${repo_root}"

source dev/lib/env
source dev/lib/common

echo -e "⧖ Cleaning old artifacts"
forge clean &> forge_clean.log
if [ $? -ne 0 ]; then
  echo "ERROR: Failed to clean old artifacts"
  cat forge_clean.log
  exit 1
fi
rm forge_clean.log
echo -e "✔ Old artifacts cleaned successfully\n"

echo -e "⧖ Updating dependencies"
forge soldeer update &> forge_soldeer_update.log
if [ $? -ne 0 ]; then
  echo "ERROR: Failed to update dependencies"
  cat forge_soldeer_update.log
  exit 1
fi
rm forge_soldeer_update.log
echo -e "✔ Dependencies updated successfully\n"

echo -e "⧖ Building contracts"
forge build &> forge_build.log
if [ $? -ne 0 ]; then
  echo "ERROR: Failed to build contracts"
  cat forge_build.log
  exit 1
fi
rm forge_build.log
echo -e "✔ Contracts built successfully\n"

echo -e "⧖ Running contract tests"
forge test &> forge_test.log
if [ $? -ne 0 ]; then
  echo "ERROR: Tests failed"
  cat forge_test.log
  exit 1
fi
rm forge_test.log
echo -e "✔ Tests passed successfully\n"

forge_deploy_script group_messages
forge_deploy_script identity_updates
forge_deploy_script nodes src/Nodes.sol Nodes
