#!/bin/bash
# Deploy the smart contracts to the local anvil node
set -euo pipefail

# Make sure the build directory exists
mkdir -p ./build

# Always work from the contracts directory
script_dir=$(dirname "$(realpath "$0")")
repo_root=$(realpath "${script_dir}/../")
cd "${repo_root}"

source dev/lib/env
source dev/lib/common

# Update depencencies
forge soldeer update &> /dev/null
if [ $? -ne 0 ]; then
  echo "ERROR: Failed to update dependencies"
  exit 1
fi

forge_deploy_script group_messages
forge_deploy_script identity_updates
forge_deploy_script nodes src/Nodes.sol Nodes
