#!/bin/bash
set -euo pipefail

############################################
# Work always from the contracts directory #
############################################
export source_dir="${SOURCE_DIR:-src}"
export build_dir="${BUILD_DIR:-build}"
export output_dir="${OUTPUT_DIR:-pkg}"

script_dir=$(dirname "$(realpath "$0")")
repo_root=$(realpath "${script_dir}/../")
cd "${repo_root}"

mkdir -p "${build_dir}" "${output_dir}"

function generate_bindings() {
    local filename="$1"
    local package="$(echo "${filename}" | tr '[:upper:]' '[:lower:]')"
    local source_artifact="${source_dir}/${filename}.sol"
    local build_artifact="${build_dir}/${filename}"
    local output_artifact="${output_dir}/${package}/${filename}.go"

    rm -f "${build_artifact}".*.json
    mkdir -p "${output_dir}/${package}"
    rm -f "${output_dir}/${package}"/*.go

    # Generate ABI and bytecode
    if ! forge inspect "${source_artifact}:${filename}" abi --json > "${build_artifact}.abi.json"; then
        echo "ERROR: Failed to generate ABI for ${filename}" >&2
        exit 1
    fi

    if ! forge inspect "${source_artifact}:${filename}" bytecode > "${build_artifact}.bin.json"; then
        echo "ERROR: Failed to generate bytecode for ${filename}" >&2
        exit 1
    fi

    # Generate Go bindings
    if ! go tool --modfile=../tools/go.mod abigen --abi "${build_artifact}.abi.json" \
                --bin "${build_artifact}.bin.json" \
                --pkg "${package}" \
                --type "${filename}" \
                --out "${output_artifact}"; then
        echo "ERROR: Failed to generate bindings for ${filename}" >&2
        exit 1
    fi
}

function main() {
    # Define contracts (pass as arguments or use a default list)
    local contracts=("$@")
    if [ "${#contracts[@]}" -eq 0 ]; then
        contracts=("Nodes" "RatesManager")
    fi

    # Generate bindings for each contract
    for contract in "${contracts[@]}"; do
        echo "⧖ Generating ABIs for contract: ${contract}"
        generate_bindings "${contract}"
    done
    echo -e "\033[32m✔\033[0m ABIs generated successfully!\n"
}

#################################################
# Generate the smart contracts bindings for Go  #
#################################################

source dev/lib/common

forge_clean
forge_soldeer_update
main "$@"
