// leave_request.proto
// This file defines the LeaveRequest message type and is associated with the following ContentTypeId:
//
// ContentTypeId {
//     authority_id: "xmtp.org",
//     type_id:      "leaveRequest",
//     version_major: 1,
//     version_minor: 0,
// }
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: mls/message_contents/content_types/leave_request.proto

package content_types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LeaveRequest message type
type LeaveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A serialized AuthenticatedNote containing the sender's signed, member-only verifiable statement
	AuthenticatedNote []byte `protobuf:"bytes,1,opt,name=authenticated_note,json=authenticatedNote,proto3,oneof" json:"authenticated_note,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_mls_message_contents_content_types_leave_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mls_message_contents_content_types_leave_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_mls_message_contents_content_types_leave_request_proto_rawDescGZIP(), []int{0}
}

func (x *LeaveRequest) GetAuthenticatedNote() []byte {
	if x != nil {
		return x.AuthenticatedNote
	}
	return nil
}

var File_mls_message_contents_content_types_leave_request_proto protoreflect.FileDescriptor

const file_mls_message_contents_content_types_leave_request_proto_rawDesc = "" +
	"\n" +
	"6mls/message_contents/content_types/leave_request.proto\x12'xmtp.mls.message_contents.content_types\"Y\n" +
	"\fLeaveRequest\x122\n" +
	"\x12authenticated_note\x18\x01 \x01(\fH\x00R\x11authenticatedNote\x88\x01\x01B\x15\n" +
	"\x13_authenticated_noteB\xbc\x02\n" +
	"+com.xmtp.mls.message_contents.content_typesB\x11LeaveRequestProtoP\x01ZBgithub.com/xmtp/xmtpd/pkg/proto/mls/message_contents/content_types\xa2\x02\x04XMMC\xaa\x02%Xmtp.Mls.MessageContents.ContentTypes\xca\x02%Xmtp\\Mls\\MessageContents\\ContentTypes\xe2\x021Xmtp\\Mls\\MessageContents\\ContentTypes\\GPBMetadata\xea\x02(Xmtp::Mls::MessageContents::ContentTypesb\x06proto3"

var (
	file_mls_message_contents_content_types_leave_request_proto_rawDescOnce sync.Once
	file_mls_message_contents_content_types_leave_request_proto_rawDescData []byte
)

func file_mls_message_contents_content_types_leave_request_proto_rawDescGZIP() []byte {
	file_mls_message_contents_content_types_leave_request_proto_rawDescOnce.Do(func() {
		file_mls_message_contents_content_types_leave_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mls_message_contents_content_types_leave_request_proto_rawDesc), len(file_mls_message_contents_content_types_leave_request_proto_rawDesc)))
	})
	return file_mls_message_contents_content_types_leave_request_proto_rawDescData
}

var file_mls_message_contents_content_types_leave_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mls_message_contents_content_types_leave_request_proto_goTypes = []any{
	(*LeaveRequest)(nil), // 0: xmtp.mls.message_contents.content_types.LeaveRequest
}
var file_mls_message_contents_content_types_leave_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mls_message_contents_content_types_leave_request_proto_init() }
func file_mls_message_contents_content_types_leave_request_proto_init() {
	if File_mls_message_contents_content_types_leave_request_proto != nil {
		return
	}
	file_mls_message_contents_content_types_leave_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mls_message_contents_content_types_leave_request_proto_rawDesc), len(file_mls_message_contents_content_types_leave_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mls_message_contents_content_types_leave_request_proto_goTypes,
		DependencyIndexes: file_mls_message_contents_content_types_leave_request_proto_depIdxs,
		MessageInfos:      file_mls_message_contents_content_types_leave_request_proto_msgTypes,
	}.Build()
	File_mls_message_contents_content_types_leave_request_proto = out.File
	file_mls_message_contents_content_types_leave_request_proto_goTypes = nil
	file_mls_message_contents_content_types_leave_request_proto_depIdxs = nil
}
