// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: configuration.sql

package queries

import (
	"context"
)

const setLocalWorkMem = `-- name: SetLocalWorkMem :one
SELECT set_config('work_mem', $1::TEXT, true)
`

func (q *Queries) SetLocalWorkMem(ctx context.Context, dollar_1 string) (string, error) {
	row := q.db.QueryRowContext(ctx, setLocalWorkMem, dollar_1)
	var set_config string
	err := row.Scan(&set_config)
	return set_config, err
}
