// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: envelopes.sql

package queries

import (
	"context"
	"time"

	"github.com/lib/pq"
)

const bulkDeleteStagedOriginatorEnvelopes = `-- name: BulkDeleteStagedOriginatorEnvelopes :execrows
DELETE FROM staged_originator_envelopes WHERE id = ANY($1::BIGINT[])
`

func (q *Queries) BulkDeleteStagedOriginatorEnvelopes(ctx context.Context, ids []int64) (int64, error) {
	result, err := q.exec(ctx, q.bulkDeleteStagedOriginatorEnvelopesStmt, bulkDeleteStagedOriginatorEnvelopes, pq.Array(ids))
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestSequenceId = `-- name: GetLatestSequenceId :one
SELECT COALESCE((
    SELECT originator_sequence_id
    FROM gateway_envelopes_latest
    WHERE originator_node_id = $1
), 0)::BIGINT AS originator_sequence_id
`

func (q *Queries) GetLatestSequenceId(ctx context.Context, originatorNodeID int32) (int64, error) {
	row := q.queryRow(ctx, q.getLatestSequenceIdStmt, getLatestSequenceId, originatorNodeID)
	var originator_sequence_id int64
	err := row.Scan(&originator_sequence_id)
	return originator_sequence_id, err
}

const insertStagedOriginatorEnvelope = `-- name: InsertStagedOriginatorEnvelope :one
SELECT id, originator_time, topic, payer_envelope
FROM insert_staged_originator_envelope($1, $2)
`

type InsertStagedOriginatorEnvelopeParams struct {
	Topic         []byte
	PayerEnvelope []byte
}

func (q *Queries) InsertStagedOriginatorEnvelope(ctx context.Context, arg InsertStagedOriginatorEnvelopeParams) (StagedOriginatorEnvelope, error) {
	row := q.queryRow(ctx, q.insertStagedOriginatorEnvelopeStmt, insertStagedOriginatorEnvelope, arg.Topic, arg.PayerEnvelope)
	var i StagedOriginatorEnvelope
	err := row.Scan(
		&i.ID,
		&i.OriginatorTime,
		&i.Topic,
		&i.PayerEnvelope,
	)
	return i, err
}

const insertStagedOriginatorEnvelopeBatch = `-- name: InsertStagedOriginatorEnvelopeBatch :many
SELECT
    s.id::bigint             AS id,
    s.originator_time::timestamp AS originator_time,
    s.topic::bytea           AS topic,
    s.payer_envelope::bytea  AS payer_envelope
FROM insert_staged_originator_envelope_batch_v2(
             $1::bytea[],
             $2::bytea[]
     ) AS s(id, originator_time, topic, payer_envelope)
`

type InsertStagedOriginatorEnvelopeBatchParams struct {
	Topics         [][]byte
	PayerEnvelopes [][]byte
}

type InsertStagedOriginatorEnvelopeBatchRow struct {
	ID             int64
	OriginatorTime time.Time
	Topic          []byte
	PayerEnvelope  []byte
}

func (q *Queries) InsertStagedOriginatorEnvelopeBatch(ctx context.Context, arg InsertStagedOriginatorEnvelopeBatchParams) ([]InsertStagedOriginatorEnvelopeBatchRow, error) {
	rows, err := q.query(ctx, q.insertStagedOriginatorEnvelopeBatchStmt, insertStagedOriginatorEnvelopeBatch, pq.Array(arg.Topics), pq.Array(arg.PayerEnvelopes))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertStagedOriginatorEnvelopeBatchRow
	for rows.Next() {
		var i InsertStagedOriginatorEnvelopeBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginatorTime,
			&i.Topic,
			&i.PayerEnvelope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAndLockStagedEnvelopes = `-- name: SelectAndLockStagedEnvelopes :many
SELECT id, originator_time, topic, payer_envelope
FROM staged_originator_envelopes
ORDER BY id ASC
LIMIT $1
FOR UPDATE
`

func (q *Queries) SelectAndLockStagedEnvelopes(ctx context.Context, numRows int32) ([]StagedOriginatorEnvelope, error) {
	rows, err := q.query(ctx, q.selectAndLockStagedEnvelopesStmt, selectAndLockStagedEnvelopes, numRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StagedOriginatorEnvelope
	for rows.Next() {
		var i StagedOriginatorEnvelope
		if err := rows.Scan(
			&i.ID,
			&i.OriginatorTime,
			&i.Topic,
			&i.PayerEnvelope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectOriginatorNodeIDs = `-- name: SelectOriginatorNodeIDs :many
SELECT originator_node_id
FROM gateway_envelopes_latest
ORDER BY originator_node_id
`

func (q *Queries) SelectOriginatorNodeIDs(ctx context.Context) ([]int32, error) {
	rows, err := q.query(ctx, q.selectOriginatorNodeIDsStmt, selectOriginatorNodeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var originator_node_id int32
		if err := rows.Scan(&originator_node_id); err != nil {
			return nil, err
		}
		items = append(items, originator_node_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectStagedOriginatorEnvelopes = `-- name: SelectStagedOriginatorEnvelopes :many
SELECT id, originator_time, topic, payer_envelope
FROM staged_originator_envelopes
WHERE id > $1
ORDER BY id ASC
LIMIT $2
`

type SelectStagedOriginatorEnvelopesParams struct {
	LastSeenID int64
	NumRows    int32
}

func (q *Queries) SelectStagedOriginatorEnvelopes(ctx context.Context, arg SelectStagedOriginatorEnvelopesParams) ([]StagedOriginatorEnvelope, error) {
	rows, err := q.query(ctx, q.selectStagedOriginatorEnvelopesStmt, selectStagedOriginatorEnvelopes, arg.LastSeenID, arg.NumRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StagedOriginatorEnvelope
	for rows.Next() {
		var i StagedOriginatorEnvelope
		if err := rows.Scan(
			&i.ID,
			&i.OriginatorTime,
			&i.Topic,
			&i.PayerEnvelope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectVectorClock = `-- name: SelectVectorClock :many
SELECT
    originator_node_id,
    originator_sequence_id,
    gateway_time
FROM gateway_envelopes_latest
ORDER BY originator_node_id
`

func (q *Queries) SelectVectorClock(ctx context.Context) ([]GatewayEnvelopesLatest, error) {
	rows, err := q.query(ctx, q.selectVectorClockStmt, selectVectorClock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayEnvelopesLatest
	for rows.Next() {
		var i GatewayEnvelopesLatest
		if err := rows.Scan(&i.OriginatorNodeID, &i.OriginatorSequenceID, &i.GatewayTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
