// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: envelopes_v2.sql

package queries

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const insertGatewayEnvelope = `-- name: InsertGatewayEnvelope :one
WITH m AS (
    INSERT INTO gateway_envelopes_meta (
                                           originator_node_id,
                                           originator_sequence_id,
                                           topic,
                                           payer_id,
                                           gateway_time,
                                           expiry
        )
        VALUES ($1,
                $2,
                $3,
                $4,
                COALESCE($5, NOW()),
                $6)
        ON CONFLICT DO NOTHING
        RETURNING 1),
     b AS (
         INSERT INTO gateway_envelope_blobs (
                                                originator_node_id,
                                                originator_sequence_id,
                                                originator_envelope
             )
             VALUES ($1,
                     $2,
                     $7)
             ON CONFLICT DO NOTHING
             RETURNING 1)
SELECT (SELECT COUNT(*) FROM m)                            AS inserted_meta_rows,
       (SELECT COUNT(*) FROM b)                            AS inserted_blob_rows,
       (SELECT COUNT(*) FROM m) + (SELECT COUNT(*) FROM b) AS total_inserted_rows
`

type InsertGatewayEnvelopeParams struct {
	OriginatorNodeID     int32
	OriginatorSequenceID int64
	Topic                []byte
	PayerID              sql.NullInt32
	GatewayTime          interface{}
	Expiry               int64
	OriginatorEnvelope   []byte
}

type InsertGatewayEnvelopeRow struct {
	InsertedMetaRows  int64
	InsertedBlobRows  int64
	TotalInsertedRows int32
}

func (q *Queries) InsertGatewayEnvelope(ctx context.Context, arg InsertGatewayEnvelopeParams) (InsertGatewayEnvelopeRow, error) {
	row := q.db.QueryRowContext(ctx, insertGatewayEnvelope,
		arg.OriginatorNodeID,
		arg.OriginatorSequenceID,
		arg.Topic,
		arg.PayerID,
		arg.GatewayTime,
		arg.Expiry,
		arg.OriginatorEnvelope,
	)
	var i InsertGatewayEnvelopeRow
	err := row.Scan(&i.InsertedMetaRows, &i.InsertedBlobRows, &i.TotalInsertedRows)
	return i, err
}

const selectGatewayEnvelopesByOriginators = `-- name: SelectGatewayEnvelopesByOriginators :many
WITH cursors AS (
    SELECT x.node_id AS cursor_node_id, y.seq_id AS cursor_sequence_id
    FROM unnest($3::INT[]) WITH ORDINALITY AS x(node_id, ord)
             JOIN unnest($4::BIGINT[]) WITH ORDINALITY AS y(seq_id, ord)
                  USING (ord)
)
SELECT v.originator_node_id,
       v.originator_sequence_id,
       v.gateway_time,
       v.topic,
       v.originator_envelope
FROM gateway_envelopes_view v
         LEFT JOIN cursors c
                   ON v.originator_node_id = c.cursor_node_id
WHERE v.originator_node_id = ANY($1::INT[])
  AND v.originator_sequence_id > COALESCE(c.cursor_sequence_id, 0)
ORDER BY v.gateway_time, v.originator_node_id, v.originator_sequence_id
LIMIT NULLIF($2::INT, 0)
`

type SelectGatewayEnvelopesByOriginatorsParams struct {
	OriginatorNodeIds []int32
	RowLimit          int32
	CursorNodeIds     []int32
	CursorSequenceIds []int64
}

func (q *Queries) SelectGatewayEnvelopesByOriginators(ctx context.Context, arg SelectGatewayEnvelopesByOriginatorsParams) ([]GatewayEnvelopesView, error) {
	rows, err := q.db.QueryContext(ctx, selectGatewayEnvelopesByOriginators,
		pq.Array(arg.OriginatorNodeIds),
		arg.RowLimit,
		pq.Array(arg.CursorNodeIds),
		pq.Array(arg.CursorSequenceIds),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayEnvelopesView
	for rows.Next() {
		var i GatewayEnvelopesView
		if err := rows.Scan(
			&i.OriginatorNodeID,
			&i.OriginatorSequenceID,
			&i.GatewayTime,
			&i.Topic,
			&i.OriginatorEnvelope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectGatewayEnvelopesByTopics = `-- name: SelectGatewayEnvelopesByTopics :many
WITH cursors AS (
    SELECT x.node_id AS cursor_node_id, y.seq_id AS cursor_sequence_id
    FROM unnest($3::INT[]) WITH ORDINALITY AS x(node_id, ord)
             JOIN unnest($4::BIGINT[]) WITH ORDINALITY AS y(seq_id, ord)
                  USING (ord)
)
SELECT v.originator_node_id,
       v.originator_sequence_id,
       v.gateway_time,
       v.topic,
       v.originator_envelope
FROM gateway_envelopes_view v
         LEFT JOIN cursors c
                   ON v.originator_node_id = c.cursor_node_id
WHERE v.topic = ANY($1::BYTEA[])
  AND v.originator_sequence_id > COALESCE(c.cursor_sequence_id, 0)
ORDER BY v.gateway_time, v.originator_node_id, v.originator_sequence_id
LIMIT NULLIF($2::INT, 0)
`

type SelectGatewayEnvelopesByTopicsParams struct {
	Topics            [][]byte
	RowLimit          int32
	CursorNodeIds     []int32
	CursorSequenceIds []int64
}

func (q *Queries) SelectGatewayEnvelopesByTopics(ctx context.Context, arg SelectGatewayEnvelopesByTopicsParams) ([]GatewayEnvelopesView, error) {
	rows, err := q.db.QueryContext(ctx, selectGatewayEnvelopesByTopics,
		pq.Array(arg.Topics),
		arg.RowLimit,
		pq.Array(arg.CursorNodeIds),
		pq.Array(arg.CursorSequenceIds),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayEnvelopesView
	for rows.Next() {
		var i GatewayEnvelopesView
		if err := rows.Scan(
			&i.OriginatorNodeID,
			&i.OriginatorSequenceID,
			&i.GatewayTime,
			&i.Topic,
			&i.OriginatorEnvelope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectGatewayEnvelopesUnfiltered = `-- name: SelectGatewayEnvelopesUnfiltered :many
WITH cursors AS (SELECT x.node_id AS cursor_node_id, y.seq_id AS cursor_sequence_id
                 FROM unnest($2::INT[]) WITH ORDINALITY AS x(node_id, ord)
                          JOIN unnest($3::BIGINT[]) WITH ORDINALITY AS y(seq_id, ord)
                               USING (ord))
SELECT v.originator_node_id,
       v.originator_sequence_id,
       v.gateway_time,
       v.topic,
       v.originator_envelope
FROM gateway_envelopes_view v
         LEFT JOIN cursors c
                   ON v.originator_node_id = c.cursor_node_id
WHERE v.originator_sequence_id > COALESCE(c.cursor_sequence_id, 0)
ORDER BY v.gateway_time,
         v.originator_node_id,
         v.originator_sequence_id
LIMIT NULLIF($1::INT, 0)
`

type SelectGatewayEnvelopesUnfilteredParams struct {
	RowLimit          int32
	CursorNodeIds     []int32
	CursorSequenceIds []int64
}

func (q *Queries) SelectGatewayEnvelopesUnfiltered(ctx context.Context, arg SelectGatewayEnvelopesUnfilteredParams) ([]GatewayEnvelopesView, error) {
	rows, err := q.db.QueryContext(ctx, selectGatewayEnvelopesUnfiltered, arg.RowLimit, pq.Array(arg.CursorNodeIds), pq.Array(arg.CursorSequenceIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GatewayEnvelopesView
	for rows.Next() {
		var i GatewayEnvelopesView
		if err := rows.Scan(
			&i.OriginatorNodeID,
			&i.OriginatorSequenceID,
			&i.GatewayTime,
			&i.Topic,
			&i.OriginatorEnvelope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectNewestFromTopics = `-- name: SelectNewestFromTopics :many
WITH latest AS (SELECT DISTINCT ON (m.topic) m.originator_node_id,
                                             m.originator_sequence_id,
                                             m.gateway_time,
                                             m.topic
                FROM gateway_envelopes_meta m
                WHERE m.topic = ANY ($1::BYTEA[])
                ORDER BY m.topic, m.gateway_time DESC)
SELECT l.originator_node_id,
       l.originator_sequence_id,
       l.gateway_time,
       l.topic,
       b.originator_envelope
FROM latest l
         JOIN gateway_envelope_blobs b
              ON b.originator_node_id = l.originator_node_id
                  AND b.originator_sequence_id = l.originator_sequence_id
ORDER BY l.topic
`

type SelectNewestFromTopicsRow struct {
	OriginatorNodeID     int32
	OriginatorSequenceID int64
	GatewayTime          time.Time
	Topic                []byte
	OriginatorEnvelope   []byte
}

func (q *Queries) SelectNewestFromTopics(ctx context.Context, topics [][]byte) ([]SelectNewestFromTopicsRow, error) {
	rows, err := q.db.QueryContext(ctx, selectNewestFromTopics, pq.Array(topics))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectNewestFromTopicsRow
	for rows.Next() {
		var i SelectNewestFromTopicsRow
		if err := rows.Scan(
			&i.OriginatorNodeID,
			&i.OriginatorSequenceID,
			&i.GatewayTime,
			&i.Topic,
			&i.OriginatorEnvelope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
