// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: migrator.sql

package queries

import (
	"context"
)

const getMigrationProgress = `-- name: GetMigrationProgress :one

SELECT last_migrated_id 
FROM migration_tracker 
WHERE source_table = $1
`

// Migration Tracker Operations
func (q *Queries) GetMigrationProgress(ctx context.Context, sourceTable string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMigrationProgress, sourceTable)
	var last_migrated_id int64
	err := row.Scan(&last_migrated_id)
	return last_migrated_id, err
}

const updateMigrationProgress = `-- name: UpdateMigrationProgress :exec
UPDATE migration_tracker 
SET last_migrated_id = $1,
    updated_at = NOW()
WHERE source_table = $2
`

type UpdateMigrationProgressParams struct {
	LastMigratedID int64
	SourceTable    string
}

func (q *Queries) UpdateMigrationProgress(ctx context.Context, arg UpdateMigrationProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateMigrationProgress, arg.LastMigratedID, arg.SourceTable)
	return err
}
