// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"
)

type AddressLog struct {
	Address               string
	InboxID               []byte
	AssociationSequenceID sql.NullInt64
	RevocationSequenceID  sql.NullInt64
}

type BlockchainMessage struct {
	BlockNumber          uint64
	BlockHash            []byte
	OriginatorNodeID     int32
	OriginatorSequenceID int64
	IsCanonical          bool
}

type GatewayEnvelope struct {
	GatewayTime          time.Time
	OriginatorNodeID     int32
	OriginatorSequenceID int64
	Topic                []byte
	OriginatorEnvelope   []byte
	PayerID              sql.NullInt32
	Expiry               sql.NullInt64
}

type LatestBlock struct {
	ContractAddress string
	BlockNumber     int64
	BlockHash       []byte
}

type MigrationTracker struct {
	SourceTable    string
	LastMigratedID int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type NodeInfo struct {
	NodeID      int32
	PublicKey   []byte
	SingletonID int16
}

type NonceTable struct {
	Nonce     int64
	CreatedAt sql.NullTime
}

type OriginatorCongestion struct {
	OriginatorID      int32
	NumMessages       int32
	MinutesSinceEpoch int32
}

type Payer struct {
	ID      int32
	Address string
}

type PayerReport struct {
	ID                  []byte
	OriginatorNodeID    int32
	StartSequenceID     int64
	EndSequenceID       int64
	EndMinuteSinceEpoch int32
	PayersMerkleRoot    []byte
	ActiveNodeIds       []int32
	SubmissionStatus    int16
	AttestationStatus   int16
	CreatedAt           sql.NullTime
}

type PayerReportAttestation struct {
	PayerReportID []byte
	NodeID        int64
	Signature     []byte
	CreatedAt     sql.NullTime
}

type StagedOriginatorEnvelope struct {
	ID             int64
	OriginatorTime time.Time
	Topic          []byte
	PayerEnvelope  []byte
}

type UnsettledUsage struct {
	PayerID           int32
	OriginatorID      int32
	MinutesSinceEpoch int32
	SpendPicodollars  int64
	LastSequenceID    int64
	MessageCount      int32
}
