// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package queries

import (
	"context"
)

const insertStagedOriginatorEnvelope = `-- name: InsertStagedOriginatorEnvelope :one
INSERT INTO staged_originator_envelopes(payer_envelope)
	VALUES ($1)
RETURNING
	id, originator_time, payer_envelope
`

func (q *Queries) InsertStagedOriginatorEnvelope(ctx context.Context, payerEnvelope []byte) (StagedOriginatorEnvelope, error) {
	row := q.db.QueryRowContext(ctx, insertStagedOriginatorEnvelope, payerEnvelope)
	var i StagedOriginatorEnvelope
	err := row.Scan(&i.ID, &i.OriginatorTime, &i.PayerEnvelope)
	return i, err
}
