#!/bin/bash
set -eou pipefail
set -a; source .env.local; set +a
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

plan="${PLAN:-devnet-local}"
plan_dir="${script_dir}/plans/${plan}"

if [ ! -d "${plan_dir}" ]; then
    echo "${plan_dir} does not exist"
    exit 1
fi

apply_path="${plan_dir}/apply.sh"

if [ -f "${apply_path}" ]; then
    cd "${plan_dir}"
    ./apply.sh
else
    "${script_dir}"/tf apply -auto-approve
fi
