#!/bin/bash
set -eou pipefail

terraform fmt -check -recursive

tflint \
    --recursive \
    --disable-rule=terraform_typed_variables \
    --disable-rule=terraform_required_providers \
    --disable-rule=terraform_required_version \
    "$@"
