#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

plan="${PLAN:-devnet-local}"
plan_dir="${script_dir}/plans/${plan}"

function tf() {
    terraform -chdir="${plan_dir}" "$@"
}

tf "$@"
