// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package worker

import (
	"context"
)

const listPartitions = `-- name: ListPartitions :many
SELECT table_name
FROM information_schema.tables
WHERE table_name LIKE 'gateway_envelopes_meta%'
ORDER BY table_name
`

func (q *Queries) ListPartitions(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPartitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var table_name string
		if err := rows.Scan(&table_name); err != nil {
			return nil, err
		}
		items = append(items, table_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
