#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
set -a; source "${script_dir}/.env.default"; set +a

GIT_COMMIT="$(git rev-parse HEAD)"
GO_VERSION="$(go list -f "{{.GoVersion}}" -m)"

docker build \
    --tag "${BUILD_CONTAINER_IMAGE}" \
    --build-arg="GO_VERSION=${GO_VERSION}" \
    --build-arg="COMMIT=${GIT_COMMIT}" \
    -f "${script_dir}/Dockerfile" \
    .
