// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: xmtpv4/metadata_api/metadata_api.proto

/*
Package metadata_api is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package metadata_api

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_MetadataApi_GetSyncCursor_0(ctx context.Context, marshaler runtime.Marshaler, client MetadataApiClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetSyncCursorRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.GetSyncCursor(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_MetadataApi_GetSyncCursor_0(ctx context.Context, marshaler runtime.Marshaler, server MetadataApiServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GetSyncCursorRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.GetSyncCursor(ctx, &protoReq)
	return msg, metadata, err

}

func request_MetadataApi_SubscribeSyncCursor_0(ctx context.Context, marshaler runtime.Marshaler, client MetadataApiClient, req *http.Request, pathParams map[string]string) (MetadataApi_SubscribeSyncCursorClient, runtime.ServerMetadata, error) {
	var protoReq GetSyncCursorRequest
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	stream, err := client.SubscribeSyncCursor(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil

}

// RegisterMetadataApiHandlerServer registers the http handlers for service MetadataApi to "mux".
// UnaryRPC     :call MetadataApiServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterMetadataApiHandlerFromEndpoint instead.
func RegisterMetadataApiHandlerServer(ctx context.Context, mux *runtime.ServeMux, server MetadataApiServer) error {

	mux.Handle("POST", pattern_MetadataApi_GetSyncCursor_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/xmtp.xmtpv4.metadata_api.MetadataApi/GetSyncCursor", runtime.WithHTTPPathPattern("/mls/v2/metadata/get-sync-cursor"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_MetadataApi_GetSyncCursor_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_MetadataApi_GetSyncCursor_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_MetadataApi_SubscribeSyncCursor_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		err := status.Error(codes.Unimplemented, "streaming calls are not yet supported in the in-process transport")
		_, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
		return
	})

	return nil
}

// RegisterMetadataApiHandlerFromEndpoint is same as RegisterMetadataApiHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterMetadataApiHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterMetadataApiHandler(ctx, mux, conn)
}

// RegisterMetadataApiHandler registers the http handlers for service MetadataApi to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterMetadataApiHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterMetadataApiHandlerClient(ctx, mux, NewMetadataApiClient(conn))
}

// RegisterMetadataApiHandlerClient registers the http handlers for service MetadataApi
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "MetadataApiClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "MetadataApiClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "MetadataApiClient" to call the correct interceptors.
func RegisterMetadataApiHandlerClient(ctx context.Context, mux *runtime.ServeMux, client MetadataApiClient) error {

	mux.Handle("POST", pattern_MetadataApi_GetSyncCursor_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/xmtp.xmtpv4.metadata_api.MetadataApi/GetSyncCursor", runtime.WithHTTPPathPattern("/mls/v2/metadata/get-sync-cursor"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_MetadataApi_GetSyncCursor_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_MetadataApi_GetSyncCursor_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("POST", pattern_MetadataApi_SubscribeSyncCursor_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/xmtp.xmtpv4.metadata_api.MetadataApi/SubscribeSyncCursor", runtime.WithHTTPPathPattern("/mls/v2/metadata/subscribe-sync-cursor"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_MetadataApi_SubscribeSyncCursor_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_MetadataApi_SubscribeSyncCursor_0(annotatedContext, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_MetadataApi_GetSyncCursor_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3}, []string{"mls", "v2", "metadata", "get-sync-cursor"}, ""))

	pattern_MetadataApi_SubscribeSyncCursor_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3}, []string{"mls", "v2", "metadata", "subscribe-sync-cursor"}, ""))
)

var (
	forward_MetadataApi_GetSyncCursor_0 = runtime.ForwardResponseMessage

	forward_MetadataApi_SubscribeSyncCursor_0 = runtime.ForwardResponseStream
)
