#!/bin/bash
set -eu

# Work always from the root directory
script_dir=$(dirname "$(realpath "$0")")
repo_root=$(realpath "${script_dir}/../../")
cd "${repo_root}"

export XMTPD_LOG_ENCODING=json

go run -ldflags="-X main.Version=$(git describe HEAD --tags --long)" cmd/cli/main.go "$@"
