#!/bin/bash
# Deploy the smart contracts to the local anvil node and log the resulting JSON

source dev/contracts/.env

cd ./contracts

# Update depencencies
forge soldeer install

forge create --legacy --json --broadcast --rpc-url $DOCKER_RPC_URL --private-key $PRIVATE_KEY "$1:$2"