#!/bin/bash

set -e

PACKAGE_NAME="abis"
BUILD_DIR="build"
OUTPUT_DIR="pkg/abis"

mkdir -p ./build
rm -f ./build/*.abi.json
rm -f ./pkg/abis/*.go

function generate_bindings() {
    cd contracts
    forge inspect ./src/${1}.sol:${1} abi > ../${BUILD_DIR}/${1}.abi.json
    forge inspect ./src/${1}.sol:${1} bytecode > ../${BUILD_DIR}/${1}.bin.json

    cd ..
    abigen --abi ./${BUILD_DIR}/${1}.abi.json --bin ./${BUILD_DIR}/${1}.bin.json --pkg "${PACKAGE_NAME}" --type "${1}" --out "./${OUTPUT_DIR}/${1}.go" > /dev/null 2>&1

}

for contract in Nodes GroupMessages IdentityUpdates; do
    generate_bindings $contract
done
