// Message content encoding structures

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: keystore_api/v1/keystore.proto

package keystore_apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Used to get a mapping of conversation topics to their HMAC keys
type GetConversationHmacKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationHmacKeysRequest) Reset() {
	*x = GetConversationHmacKeysRequest{}
	mi := &file_keystore_api_v1_keystore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationHmacKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationHmacKeysRequest) ProtoMessage() {}

func (x *GetConversationHmacKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_api_v1_keystore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationHmacKeysRequest.ProtoReflect.Descriptor instead.
func (*GetConversationHmacKeysRequest) Descriptor() ([]byte, []int) {
	return file_keystore_api_v1_keystore_proto_rawDescGZIP(), []int{0}
}

func (x *GetConversationHmacKeysRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// A mapping of topics to their HMAC keys
type GetConversationHmacKeysResponse struct {
	state         protoimpl.MessageState                               `protogen:"open.v1"`
	HmacKeys      map[string]*GetConversationHmacKeysResponse_HmacKeys `protobuf:"bytes,1,rep,name=hmac_keys,json=hmacKeys,proto3" json:"hmac_keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationHmacKeysResponse) Reset() {
	*x = GetConversationHmacKeysResponse{}
	mi := &file_keystore_api_v1_keystore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationHmacKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationHmacKeysResponse) ProtoMessage() {}

func (x *GetConversationHmacKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_api_v1_keystore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationHmacKeysResponse.ProtoReflect.Descriptor instead.
func (*GetConversationHmacKeysResponse) Descriptor() ([]byte, []int) {
	return file_keystore_api_v1_keystore_proto_rawDescGZIP(), []int{1}
}

func (x *GetConversationHmacKeysResponse) GetHmacKeys() map[string]*GetConversationHmacKeysResponse_HmacKeys {
	if x != nil {
		return x.HmacKeys
	}
	return nil
}

// HmacKeyData wraps the HMAC key and the number of 30 day periods since epoch
type GetConversationHmacKeysResponse_HmacKeyData struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ThirtyDayPeriodsSinceEpoch int32                  `protobuf:"varint,1,opt,name=thirty_day_periods_since_epoch,json=thirtyDayPeriodsSinceEpoch,proto3" json:"thirty_day_periods_since_epoch,omitempty"`
	HmacKey                    []byte                 `protobuf:"bytes,2,opt,name=hmac_key,json=hmacKey,proto3" json:"hmac_key,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetConversationHmacKeysResponse_HmacKeyData) Reset() {
	*x = GetConversationHmacKeysResponse_HmacKeyData{}
	mi := &file_keystore_api_v1_keystore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationHmacKeysResponse_HmacKeyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationHmacKeysResponse_HmacKeyData) ProtoMessage() {}

func (x *GetConversationHmacKeysResponse_HmacKeyData) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_api_v1_keystore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationHmacKeysResponse_HmacKeyData.ProtoReflect.Descriptor instead.
func (*GetConversationHmacKeysResponse_HmacKeyData) Descriptor() ([]byte, []int) {
	return file_keystore_api_v1_keystore_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetConversationHmacKeysResponse_HmacKeyData) GetThirtyDayPeriodsSinceEpoch() int32 {
	if x != nil {
		return x.ThirtyDayPeriodsSinceEpoch
	}
	return 0
}

func (x *GetConversationHmacKeysResponse_HmacKeyData) GetHmacKey() []byte {
	if x != nil {
		return x.HmacKey
	}
	return nil
}

// HmacKeys represents multiple HmacKeyData objects
type GetConversationHmacKeysResponse_HmacKeys struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Values        []*GetConversationHmacKeysResponse_HmacKeyData `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationHmacKeysResponse_HmacKeys) Reset() {
	*x = GetConversationHmacKeysResponse_HmacKeys{}
	mi := &file_keystore_api_v1_keystore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationHmacKeysResponse_HmacKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationHmacKeysResponse_HmacKeys) ProtoMessage() {}

func (x *GetConversationHmacKeysResponse_HmacKeys) ProtoReflect() protoreflect.Message {
	mi := &file_keystore_api_v1_keystore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationHmacKeysResponse_HmacKeys.ProtoReflect.Descriptor instead.
func (*GetConversationHmacKeysResponse_HmacKeys) Descriptor() ([]byte, []int) {
	return file_keystore_api_v1_keystore_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetConversationHmacKeysResponse_HmacKeys) GetValues() []*GetConversationHmacKeysResponse_HmacKeyData {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_keystore_api_v1_keystore_proto protoreflect.FileDescriptor

const file_keystore_api_v1_keystore_proto_rawDesc = "" +
	"\n" +
	"\x1ekeystore_api/v1/keystore.proto\x12\x14xmtp.keystore_api.v1\"8\n" +
	"\x1eGetConversationHmacKeysRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"\xd5\x03\n" +
	"\x1fGetConversationHmacKeysResponse\x12`\n" +
	"\thmac_keys\x18\x01 \x03(\v2C.xmtp.keystore_api.v1.GetConversationHmacKeysResponse.HmacKeysEntryR\bhmacKeys\x1al\n" +
	"\vHmacKeyData\x12B\n" +
	"\x1ethirty_day_periods_since_epoch\x18\x01 \x01(\x05R\x1athirtyDayPeriodsSinceEpoch\x12\x19\n" +
	"\bhmac_key\x18\x02 \x01(\fR\ahmacKey\x1ae\n" +
	"\bHmacKeys\x12Y\n" +
	"\x06values\x18\x01 \x03(\v2A.xmtp.keystore_api.v1.GetConversationHmacKeysResponse.HmacKeyDataR\x06values\x1a{\n" +
	"\rHmacKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12T\n" +
	"\x05value\x18\x02 \x01(\v2>.xmtp.keystore_api.v1.GetConversationHmacKeysResponse.HmacKeysR\x05value:\x028\x01B\xd7\x01\n" +
	"\x18com.xmtp.keystore_api.v1B\rKeystoreProtoP\x01Z>github.com/xmtp/xmtpd/pkg/proto/keystore_api/v1;keystore_apiv1\xa2\x02\x03XKX\xaa\x02\x13Xmtp.KeystoreApi.V1\xca\x02\x13Xmtp\\KeystoreApi\\V1\xe2\x02\x1fXmtp\\KeystoreApi\\V1\\GPBMetadata\xea\x02\x15Xmtp::KeystoreApi::V1b\x06proto3"

var (
	file_keystore_api_v1_keystore_proto_rawDescOnce sync.Once
	file_keystore_api_v1_keystore_proto_rawDescData []byte
)

func file_keystore_api_v1_keystore_proto_rawDescGZIP() []byte {
	file_keystore_api_v1_keystore_proto_rawDescOnce.Do(func() {
		file_keystore_api_v1_keystore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keystore_api_v1_keystore_proto_rawDesc), len(file_keystore_api_v1_keystore_proto_rawDesc)))
	})
	return file_keystore_api_v1_keystore_proto_rawDescData
}

var file_keystore_api_v1_keystore_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_keystore_api_v1_keystore_proto_goTypes = []any{
	(*GetConversationHmacKeysRequest)(nil),              // 0: xmtp.keystore_api.v1.GetConversationHmacKeysRequest
	(*GetConversationHmacKeysResponse)(nil),             // 1: xmtp.keystore_api.v1.GetConversationHmacKeysResponse
	(*GetConversationHmacKeysResponse_HmacKeyData)(nil), // 2: xmtp.keystore_api.v1.GetConversationHmacKeysResponse.HmacKeyData
	(*GetConversationHmacKeysResponse_HmacKeys)(nil),    // 3: xmtp.keystore_api.v1.GetConversationHmacKeysResponse.HmacKeys
	nil, // 4: xmtp.keystore_api.v1.GetConversationHmacKeysResponse.HmacKeysEntry
}
var file_keystore_api_v1_keystore_proto_depIdxs = []int32{
	4, // 0: xmtp.keystore_api.v1.GetConversationHmacKeysResponse.hmac_keys:type_name -> xmtp.keystore_api.v1.GetConversationHmacKeysResponse.HmacKeysEntry
	2, // 1: xmtp.keystore_api.v1.GetConversationHmacKeysResponse.HmacKeys.values:type_name -> xmtp.keystore_api.v1.GetConversationHmacKeysResponse.HmacKeyData
	3, // 2: xmtp.keystore_api.v1.GetConversationHmacKeysResponse.HmacKeysEntry.value:type_name -> xmtp.keystore_api.v1.GetConversationHmacKeysResponse.HmacKeys
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_keystore_api_v1_keystore_proto_init() }
func file_keystore_api_v1_keystore_proto_init() {
	if File_keystore_api_v1_keystore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keystore_api_v1_keystore_proto_rawDesc), len(file_keystore_api_v1_keystore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keystore_api_v1_keystore_proto_goTypes,
		DependencyIndexes: file_keystore_api_v1_keystore_proto_depIdxs,
		MessageInfos:      file_keystore_api_v1_keystore_proto_msgTypes,
	}.Build()
	File_keystore_api_v1_keystore_proto = out.File
	file_keystore_api_v1_keystore_proto_goTypes = nil
	file_keystore_api_v1_keystore_proto_depIdxs = nil
}
