// Holds the ConversationReference

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: message_contents/conversation_reference.proto

package message_contents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A light pointer for a conversation that contains no decryption keys
type ConversationReference struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Topic               string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PeerAddress         string                 `protobuf:"bytes,2,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	CreatedNs           uint64                 `protobuf:"varint,3,opt,name=created_ns,json=createdNs,proto3" json:"created_ns,omitempty"`
	Context             *InvitationV1_Context  `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	ConsentProofPayload *ConsentProofPayload   `protobuf:"bytes,5,opt,name=consent_proof_payload,json=consentProofPayload,proto3" json:"consent_proof_payload,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConversationReference) Reset() {
	*x = ConversationReference{}
	mi := &file_message_contents_conversation_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationReference) ProtoMessage() {}

func (x *ConversationReference) ProtoReflect() protoreflect.Message {
	mi := &file_message_contents_conversation_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationReference.ProtoReflect.Descriptor instead.
func (*ConversationReference) Descriptor() ([]byte, []int) {
	return file_message_contents_conversation_reference_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationReference) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConversationReference) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *ConversationReference) GetCreatedNs() uint64 {
	if x != nil {
		return x.CreatedNs
	}
	return 0
}

func (x *ConversationReference) GetContext() *InvitationV1_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ConversationReference) GetConsentProofPayload() *ConsentProofPayload {
	if x != nil {
		return x.ConsentProofPayload
	}
	return nil
}

var File_message_contents_conversation_reference_proto protoreflect.FileDescriptor

const file_message_contents_conversation_reference_proto_rawDesc = "" +
	"\n" +
	"-message_contents/conversation_reference.proto\x12\x15xmtp.message_contents\x1a!message_contents/invitation.proto\"\x96\x02\n" +
	"\x15ConversationReference\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12!\n" +
	"\fpeer_address\x18\x02 \x01(\tR\vpeerAddress\x12\x1d\n" +
	"\n" +
	"created_ns\x18\x03 \x01(\x04R\tcreatedNs\x12E\n" +
	"\acontext\x18\x04 \x01(\v2+.xmtp.message_contents.InvitationV1.ContextR\acontext\x12^\n" +
	"\x15consent_proof_payload\x18\x05 \x01(\v2*.xmtp.message_contents.ConsentProofPayloadR\x13consentProofPayloadB\xda\x01\n" +
	"\x19com.xmtp.message_contentsB\x1aConversationReferenceProtoP\x01Z0github.com/xmtp/xmtpd/pkg/proto/message_contents\xa2\x02\x03XMX\xaa\x02\x14Xmtp.MessageContents\xca\x02\x14Xmtp\\MessageContents\xe2\x02 Xmtp\\MessageContents\\GPBMetadata\xea\x02\x15Xmtp::MessageContentsb\x06proto3"

var (
	file_message_contents_conversation_reference_proto_rawDescOnce sync.Once
	file_message_contents_conversation_reference_proto_rawDescData []byte
)

func file_message_contents_conversation_reference_proto_rawDescGZIP() []byte {
	file_message_contents_conversation_reference_proto_rawDescOnce.Do(func() {
		file_message_contents_conversation_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_contents_conversation_reference_proto_rawDesc), len(file_message_contents_conversation_reference_proto_rawDesc)))
	})
	return file_message_contents_conversation_reference_proto_rawDescData
}

var file_message_contents_conversation_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_contents_conversation_reference_proto_goTypes = []any{
	(*ConversationReference)(nil), // 0: xmtp.message_contents.ConversationReference
	(*InvitationV1_Context)(nil),  // 1: xmtp.message_contents.InvitationV1.Context
	(*ConsentProofPayload)(nil),   // 2: xmtp.message_contents.ConsentProofPayload
}
var file_message_contents_conversation_reference_proto_depIdxs = []int32{
	1, // 0: xmtp.message_contents.ConversationReference.context:type_name -> xmtp.message_contents.InvitationV1.Context
	2, // 1: xmtp.message_contents.ConversationReference.consent_proof_payload:type_name -> xmtp.message_contents.ConsentProofPayload
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_contents_conversation_reference_proto_init() }
func file_message_contents_conversation_reference_proto_init() {
	if File_message_contents_conversation_reference_proto != nil {
		return
	}
	file_message_contents_invitation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_contents_conversation_reference_proto_rawDesc), len(file_message_contents_conversation_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_contents_conversation_reference_proto_goTypes,
		DependencyIndexes: file_message_contents_conversation_reference_proto_depIdxs,
		MessageInfos:      file_message_contents_conversation_reference_proto_msgTypes,
	}.Build()
	File_message_contents_conversation_reference_proto = out.File
	file_message_contents_conversation_reference_proto_goTypes = nil
	file_message_contents_conversation_reference_proto_depIdxs = nil
}
