#!/bin/bash
set -eou pipefail

. dev/net/k8s-env

nodes="$(dev/terraform/tf output -json | jq -r '.nodes.value[].name')"
opts=()
while read -r node; do
    opts+=("--api-url=http://${node}.localhost")
done <<< "$(echo -e "$nodes")"
opts+=("$@")

dev/e2e/run "${opts[*]}"
