#!/bin/bash
set -eu

# Work always from the root directory
script_dir=$(dirname "$(realpath "$0")")
repo_root=$(realpath "${script_dir}/../../")
cd "${repo_root}"

. dev/local.env

export XMTPD_SIGNER_PUBLIC_KEY=$ANVIL_ACC_2_PUBLIC_KEY
export NODE_ADDRESS=$ANVIL_ACC_2_ADDRESS
export NODE_OPERATOR_PRIVATE_KEY=$ANVIL_ACC_2_PRIVATE_KEY

NODE_ID=$(dev/cli register-node \
    --http-address=http://localhost:5051 \
    --node-owner-address=$NODE_ADDRESS \
    --admin.private-key=$PRIVATE_KEY \
    --node-signing-key-pub=$XMTPD_SIGNER_PUBLIC_KEY | jq -r '.node_id')

dev/cli/cli-cmd add-node-to-network \
    --private-key=${PRIVATE_KEY} \
    --node-id=${NODE_ID}

echo -e "\033[32m✔\033[0m Node with ID $NODE_ID has been registered and enabled"
