name: "Planning: move current tickets to next iteration"

on:
  workflow_dispatch:

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest

    steps:
      - uses: blombard/move-to-next-iteration@v0.6.1
        with:
          owner: XMTP
          number: 26
          token: ${{ secrets.PROJECT_PAT }}
          iteration-field: Iteration
          iteration: current
          new-iteration: next
          excluded-statuses: "Done,Won't Fix"