name: Contracts - Slither

on:
  push:
    branches:
      - main
    paths:
      - "contracts/src/**"
  pull_request:
    paths:
      - "contracts/src/**"

defaults:
  run:
    working-directory: ./contracts

jobs:
  slither:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.1.0"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: forge soldeer update

      - name: Build contracts
        run: forge build

      - name: Install Slither
        run: pip3 install slither-analyzer

      - name: Run Slither
        run: slither . --sarif output.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: contracts/output.sarif
