// Group-wide external-commit policy component for the app-data registry.
//
// EXTERNAL_COMMIT_POLICY is a well-known component (registered with its
// own ComponentId in the mid-range) that carries cross-cutting flags
// governing whether and how new members may join the group via MLS
// External Commits (RFC 9420 §12.4.3.2) — the QR-invite / link-invite
// flow.
//
// This component is the master switch (defense-in-depth gate) for the
// external-commit mechanism. Even when `allow_external_commit` is true,
// the actual shape and effects of an external commit are bounded by:
//
//   1. RFC 9420 / libxmtp invariants enforced in the validator
//      (exactly one ExternalInit, joiner credential binding on all Adds,
//      no by-reference proposals, no SelfRemove, etc.).
//   2. Per-component `external_committer_permissions` blocks declared on
//      each touched component's `ComponentMetadata`.
//
// In other words: EXTERNAL_COMMIT_POLICY is the runtime-toggleable
// master switch + time-window controls. `external_committer_permissions`
// is the declarative, per-component surface that says *what* an external
// committer may do once the master switch is on. Both must admit the
// commit for it to be accepted.
//
// Toggling fields at runtime is an AppDataUpdate(EXTERNAL_COMMIT_POLICY)
// proposal; the component's update policy (in its
// `ComponentMetadata.permissions`) gates who can flip the bits
// (super-admin-only by default).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: mls/message_contents/external_commit_policy.proto

package message_contents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// v1 external-commit-policy payload.
// Field-coupling invariants enforced by libxmtp when applying an
// AppDataUpdate(EXTERNAL_COMMIT_POLICY) proposal:
//
//   - When `allow_external_commit` transitions to true: `symmetric_key`
//     and `external_group_id` MUST be populated (non-empty, meeting
//     their length requirements) in the same proposal. The two
//     transitions are atomic — there is no window where the bit is on
//     but the invite coordinates are unset.
//
//   - When `allow_external_commit` transitions to false (revoke):
//     `symmetric_key` and `external_group_id` MUST be cleared (set to
//     empty bytes) in the same proposal. Leaving stale coordinates in
//     the group state after revoke would let a future re-enable
//     accidentally revive a previously-distributed key.
//
//   - On re-enable (false → true after a prior revoke): the new
//     `symmetric_key` MUST differ from every previously-used value for
//     this group, and the new `external_group_id` SHOULD differ as
//     well. Reusing a revoked key would re-validate every QR ever
//     printed under that key, defeating the revocation. Admin clients
//     are responsible for generating fresh material on each enable.
type ExternalCommitPolicyV1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Master switch for MLS External Commits adding new members.
	// Required for the QR-invite flow. Defaults to false; admins
	// (super-admin by default) opt in via
	// AppDataUpdate(EXTERNAL_COMMIT_POLICY).
	//
	// See the field-coupling invariants in the message-level comment
	// above: enabling MUST populate symmetric_key + external_group_id;
	// revoking (true → false) MUST clear them.
	AllowExternalCommit bool `protobuf:"varint,1,opt,name=allow_external_commit,json=allowExternalCommit,proto3" json:"allow_external_commit,omitempty"`
	// Wall-clock auto-disable timestamp (ns since UNIX epoch).
	// 0 = no automatic expiry. After this timestamp the validator
	// rejects all external commits regardless of `allow_external_commit`.
	// Lets admins issue time-bounded invite campaigns without having to
	// come back and flip the bit manually.
	ExpiresAtNs uint64 `protobuf:"varint,2,opt,name=expires_at_ns,json=expiresAtNs,proto3" json:"expires_at_ns,omitempty"`
	// Maximum staleness of the GroupInfo referenced by an external
	// commit, in nanoseconds since GroupInfo export. 0 = no staleness
	// limit. External commits whose referenced GroupInfo was exported
	// more than `expire_in_ns` ago are rejected. Narrows the replay
	// window for stolen-blob attacks and forces re-export frequency.
	ExpireInNs uint64 `protobuf:"varint,3,opt,name=expire_in_ns,json=expireInNs,proto3" json:"expire_in_ns,omitempty"`
	// 32-byte ChaCha20Poly1305 key used to wrap the EncryptedGroupInfoBlob
	// for the currently-active invite. Carried in the group state so any
	// member (especially a just-joined external committer) can re-export
	// GroupInfo and re-upload a refreshed blob under the same key after a
	// join — without this, a printed QR / link would die the moment the
	// issuing admin went offline.
	//
	// The QR carries the same key bytes. Rotation = admin sets a new value
	// here in a single AppDataUpdate(EXTERNAL_COMMIT_POLICY) proposal AND
	// issues a new QR carrying the matching key; old QR holders' keys no
	// longer decrypt blobs the service serves under the rotated slot.
	//
	// Length MUST be exactly 32 bytes when populated. Empty (zero-length)
	// means no active invite — and MUST coincide with
	// `allow_external_commit == false` (see the field-coupling invariants
	// at the top of this message). Revoking the invite MUST clear this
	// field; re-enabling MUST populate it with a freshly-generated value
	// distinct from any previously-used key for this group.
	//
	// Note: the service_pointer (where the blob lives) is intentionally
	// NOT stored in the group. It is per-QR application-defined opaque
	// bytes; different invites for the same group may point at different
	// services. Joiners use the service_pointer from the QR they scanned.
	SymmetricKey []byte `protobuf:"bytes,4,opt,name=symmetric_key,json=symmetricKey,proto3" json:"symmetric_key,omitempty"`
	// Identifier for the service slot holding the active invite's
	// encrypted blob. Application-defined opaque bytes (UUID, snowflake,
	// short slot key, etc.); decoupled from the MLS group_id. Admins
	// MAY rotate the symmetric_key while keeping this stable (overwrite
	// the same slot on the service) or change both together (new slot,
	// leaves the old slot orphaned for application-side GC).
	//
	// The QR carries the same value. The joiner verifies that the QR's
	// `external_group_id` equals this field after joining, as
	// defense-in-depth against a stale or swapped QR. Mismatch indicates
	// the admin rotated to a new slot after the QR was minted; the
	// joining client SHOULD treat the just-published commit as orphaned
	// (it validates fine, but the refreshed blob the joiner would upload
	// to the old slot will not be reachable by holders of the new QR).
	//
	// MUST be at least 4 bytes when populated (collision-avoidance floor
	// for tiny services). RECOMMENDED: 16 random bytes when no
	// application-specific scheme is in use. Empty (zero-length) means
	// no active invite — and MUST coincide with
	// `allow_external_commit == false` (see the field-coupling
	// invariants at the top of this message). Revoking the invite MUST
	// clear this field; re-enabling SHOULD use a freshly-generated value
	// (reusing a prior `external_group_id` is permitted only when the
	// admin intends to overwrite the old service slot — typically the
	// admin generates a new value to leave the prior slot orphaned).
	ExternalGroupId []byte `protobuf:"bytes,5,opt,name=external_group_id,json=externalGroupId,proto3" json:"external_group_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExternalCommitPolicyV1) Reset() {
	*x = ExternalCommitPolicyV1{}
	mi := &file_mls_message_contents_external_commit_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalCommitPolicyV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalCommitPolicyV1) ProtoMessage() {}

func (x *ExternalCommitPolicyV1) ProtoReflect() protoreflect.Message {
	mi := &file_mls_message_contents_external_commit_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalCommitPolicyV1.ProtoReflect.Descriptor instead.
func (*ExternalCommitPolicyV1) Descriptor() ([]byte, []int) {
	return file_mls_message_contents_external_commit_policy_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalCommitPolicyV1) GetAllowExternalCommit() bool {
	if x != nil {
		return x.AllowExternalCommit
	}
	return false
}

func (x *ExternalCommitPolicyV1) GetExpiresAtNs() uint64 {
	if x != nil {
		return x.ExpiresAtNs
	}
	return 0
}

func (x *ExternalCommitPolicyV1) GetExpireInNs() uint64 {
	if x != nil {
		return x.ExpireInNs
	}
	return 0
}

func (x *ExternalCommitPolicyV1) GetSymmetricKey() []byte {
	if x != nil {
		return x.SymmetricKey
	}
	return nil
}

func (x *ExternalCommitPolicyV1) GetExternalGroupId() []byte {
	if x != nil {
		return x.ExternalGroupId
	}
	return nil
}

// Versioned envelope. New variants are added as new oneof variants;
// readers that don't recognize a variant treat the policy as default
// (all fields zero) per the standard unknown-variant tolerance rules.
type ExternalCommitPolicyEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*ExternalCommitPolicyEntry_V1
	Version       isExternalCommitPolicyEntry_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalCommitPolicyEntry) Reset() {
	*x = ExternalCommitPolicyEntry{}
	mi := &file_mls_message_contents_external_commit_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalCommitPolicyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalCommitPolicyEntry) ProtoMessage() {}

func (x *ExternalCommitPolicyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_mls_message_contents_external_commit_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalCommitPolicyEntry.ProtoReflect.Descriptor instead.
func (*ExternalCommitPolicyEntry) Descriptor() ([]byte, []int) {
	return file_mls_message_contents_external_commit_policy_proto_rawDescGZIP(), []int{1}
}

func (x *ExternalCommitPolicyEntry) GetVersion() isExternalCommitPolicyEntry_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ExternalCommitPolicyEntry) GetV1() *ExternalCommitPolicyV1 {
	if x != nil {
		if x, ok := x.Version.(*ExternalCommitPolicyEntry_V1); ok {
			return x.V1
		}
	}
	return nil
}

type isExternalCommitPolicyEntry_Version interface {
	isExternalCommitPolicyEntry_Version()
}

type ExternalCommitPolicyEntry_V1 struct {
	V1 *ExternalCommitPolicyV1 `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*ExternalCommitPolicyEntry_V1) isExternalCommitPolicyEntry_Version() {}

var File_mls_message_contents_external_commit_policy_proto protoreflect.FileDescriptor

const file_mls_message_contents_external_commit_policy_proto_rawDesc = "" +
	"\n" +
	"1mls/message_contents/external_commit_policy.proto\x12\x19xmtp.mls.message_contents\"\xe3\x01\n" +
	"\x16ExternalCommitPolicyV1\x122\n" +
	"\x15allow_external_commit\x18\x01 \x01(\bR\x13allowExternalCommit\x12\"\n" +
	"\rexpires_at_ns\x18\x02 \x01(\x04R\vexpiresAtNs\x12 \n" +
	"\fexpire_in_ns\x18\x03 \x01(\x04R\n" +
	"expireInNs\x12#\n" +
	"\rsymmetric_key\x18\x04 \x01(\fR\fsymmetricKey\x12*\n" +
	"\x11external_group_id\x18\x05 \x01(\fR\x0fexternalGroupId\"k\n" +
	"\x19ExternalCommitPolicyEntry\x12C\n" +
	"\x02v1\x18\x01 \x01(\v21.xmtp.mls.message_contents.ExternalCommitPolicyV1H\x00R\x02v1B\t\n" +
	"\aversionB\xf2\x01\n" +
	"\x1dcom.xmtp.mls.message_contentsB\x19ExternalCommitPolicyProtoP\x01Z4github.com/xmtp/xmtpd/pkg/proto/mls/message_contents\xa2\x02\x03XMM\xaa\x02\x18Xmtp.Mls.MessageContents\xca\x02\x18Xmtp\\Mls\\MessageContents\xe2\x02$Xmtp\\Mls\\MessageContents\\GPBMetadata\xea\x02\x1aXmtp::Mls::MessageContentsb\x06proto3"

var (
	file_mls_message_contents_external_commit_policy_proto_rawDescOnce sync.Once
	file_mls_message_contents_external_commit_policy_proto_rawDescData []byte
)

func file_mls_message_contents_external_commit_policy_proto_rawDescGZIP() []byte {
	file_mls_message_contents_external_commit_policy_proto_rawDescOnce.Do(func() {
		file_mls_message_contents_external_commit_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mls_message_contents_external_commit_policy_proto_rawDesc), len(file_mls_message_contents_external_commit_policy_proto_rawDesc)))
	})
	return file_mls_message_contents_external_commit_policy_proto_rawDescData
}

var file_mls_message_contents_external_commit_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mls_message_contents_external_commit_policy_proto_goTypes = []any{
	(*ExternalCommitPolicyV1)(nil),    // 0: xmtp.mls.message_contents.ExternalCommitPolicyV1
	(*ExternalCommitPolicyEntry)(nil), // 1: xmtp.mls.message_contents.ExternalCommitPolicyEntry
}
var file_mls_message_contents_external_commit_policy_proto_depIdxs = []int32{
	0, // 0: xmtp.mls.message_contents.ExternalCommitPolicyEntry.v1:type_name -> xmtp.mls.message_contents.ExternalCommitPolicyV1
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mls_message_contents_external_commit_policy_proto_init() }
func file_mls_message_contents_external_commit_policy_proto_init() {
	if File_mls_message_contents_external_commit_policy_proto != nil {
		return
	}
	file_mls_message_contents_external_commit_policy_proto_msgTypes[1].OneofWrappers = []any{
		(*ExternalCommitPolicyEntry_V1)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mls_message_contents_external_commit_policy_proto_rawDesc), len(file_mls_message_contents_external_commit_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mls_message_contents_external_commit_policy_proto_goTypes,
		DependencyIndexes: file_mls_message_contents_external_commit_policy_proto_depIdxs,
		MessageInfos:      file_mls_message_contents_external_commit_policy_proto_msgTypes,
	}.Build()
	File_mls_message_contents_external_commit_policy_proto = out.File
	file_mls_message_contents_external_commit_policy_proto_goTypes = nil
	file_mls_message_contents_external_commit_policy_proto_depIdxs = nil
}
