// Message content encoding structures

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mls/message_contents/transcript_messages.proto

package message_contents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A group member and affected installation IDs
type MembershipChange struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	InstallationIds           [][]byte               `protobuf:"bytes,1,rep,name=installation_ids,json=installationIds,proto3" json:"installation_ids,omitempty"`
	AccountAddress            string                 `protobuf:"bytes,2,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	InitiatedByAccountAddress string                 `protobuf:"bytes,3,opt,name=initiated_by_account_address,json=initiatedByAccountAddress,proto3" json:"initiated_by_account_address,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MembershipChange) Reset() {
	*x = MembershipChange{}
	mi := &file_mls_message_contents_transcript_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipChange) ProtoMessage() {}

func (x *MembershipChange) ProtoReflect() protoreflect.Message {
	mi := &file_mls_message_contents_transcript_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipChange.ProtoReflect.Descriptor instead.
func (*MembershipChange) Descriptor() ([]byte, []int) {
	return file_mls_message_contents_transcript_messages_proto_rawDescGZIP(), []int{0}
}

func (x *MembershipChange) GetInstallationIds() [][]byte {
	if x != nil {
		return x.InstallationIds
	}
	return nil
}

func (x *MembershipChange) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

func (x *MembershipChange) GetInitiatedByAccountAddress() string {
	if x != nil {
		return x.InitiatedByAccountAddress
	}
	return ""
}

// The group membership change proto
type GroupMembershipChanges struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Members that have been added in the commit
	MembersAdded []*MembershipChange `protobuf:"bytes,1,rep,name=members_added,json=membersAdded,proto3" json:"members_added,omitempty"`
	// Members that have been removed in the commit
	MembersRemoved []*MembershipChange `protobuf:"bytes,2,rep,name=members_removed,json=membersRemoved,proto3" json:"members_removed,omitempty"`
	// Installations that have been added in the commit, grouped by member
	InstallationsAdded []*MembershipChange `protobuf:"bytes,3,rep,name=installations_added,json=installationsAdded,proto3" json:"installations_added,omitempty"`
	// Installations removed in the commit, grouped by member
	InstallationsRemoved []*MembershipChange `protobuf:"bytes,4,rep,name=installations_removed,json=installationsRemoved,proto3" json:"installations_removed,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GroupMembershipChanges) Reset() {
	*x = GroupMembershipChanges{}
	mi := &file_mls_message_contents_transcript_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembershipChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembershipChanges) ProtoMessage() {}

func (x *GroupMembershipChanges) ProtoReflect() protoreflect.Message {
	mi := &file_mls_message_contents_transcript_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembershipChanges.ProtoReflect.Descriptor instead.
func (*GroupMembershipChanges) Descriptor() ([]byte, []int) {
	return file_mls_message_contents_transcript_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMembershipChanges) GetMembersAdded() []*MembershipChange {
	if x != nil {
		return x.MembersAdded
	}
	return nil
}

func (x *GroupMembershipChanges) GetMembersRemoved() []*MembershipChange {
	if x != nil {
		return x.MembersRemoved
	}
	return nil
}

func (x *GroupMembershipChanges) GetInstallationsAdded() []*MembershipChange {
	if x != nil {
		return x.InstallationsAdded
	}
	return nil
}

func (x *GroupMembershipChanges) GetInstallationsRemoved() []*MembershipChange {
	if x != nil {
		return x.InstallationsRemoved
	}
	return nil
}

// A summary of the changes in a commit.
// Includes added/removed inboxes and changes to metadata
type GroupUpdated struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InitiatedByInboxId string                 `protobuf:"bytes,1,opt,name=initiated_by_inbox_id,json=initiatedByInboxId,proto3" json:"initiated_by_inbox_id,omitempty"`
	// The inboxes added in the commit
	AddedInboxes []*GroupUpdated_Inbox `protobuf:"bytes,2,rep,name=added_inboxes,json=addedInboxes,proto3" json:"added_inboxes,omitempty"`
	// The inboxes removed in the commit
	RemovedInboxes []*GroupUpdated_Inbox `protobuf:"bytes,3,rep,name=removed_inboxes,json=removedInboxes,proto3" json:"removed_inboxes,omitempty"`
	// The metadata changes in the commit
	MetadataFieldChanges []*GroupUpdated_MetadataFieldChange `protobuf:"bytes,4,rep,name=metadata_field_changes,json=metadataFieldChanges,proto3" json:"metadata_field_changes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GroupUpdated) Reset() {
	*x = GroupUpdated{}
	mi := &file_mls_message_contents_transcript_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUpdated) ProtoMessage() {}

func (x *GroupUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_mls_message_contents_transcript_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUpdated.ProtoReflect.Descriptor instead.
func (*GroupUpdated) Descriptor() ([]byte, []int) {
	return file_mls_message_contents_transcript_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GroupUpdated) GetInitiatedByInboxId() string {
	if x != nil {
		return x.InitiatedByInboxId
	}
	return ""
}

func (x *GroupUpdated) GetAddedInboxes() []*GroupUpdated_Inbox {
	if x != nil {
		return x.AddedInboxes
	}
	return nil
}

func (x *GroupUpdated) GetRemovedInboxes() []*GroupUpdated_Inbox {
	if x != nil {
		return x.RemovedInboxes
	}
	return nil
}

func (x *GroupUpdated) GetMetadataFieldChanges() []*GroupUpdated_MetadataFieldChange {
	if x != nil {
		return x.MetadataFieldChanges
	}
	return nil
}

// An inbox that was added or removed in this commit
type GroupUpdated_Inbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InboxId       string                 `protobuf:"bytes,1,opt,name=inbox_id,json=inboxId,proto3" json:"inbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUpdated_Inbox) Reset() {
	*x = GroupUpdated_Inbox{}
	mi := &file_mls_message_contents_transcript_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUpdated_Inbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUpdated_Inbox) ProtoMessage() {}

func (x *GroupUpdated_Inbox) ProtoReflect() protoreflect.Message {
	mi := &file_mls_message_contents_transcript_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUpdated_Inbox.ProtoReflect.Descriptor instead.
func (*GroupUpdated_Inbox) Descriptor() ([]byte, []int) {
	return file_mls_message_contents_transcript_messages_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GroupUpdated_Inbox) GetInboxId() string {
	if x != nil {
		return x.InboxId
	}
	return ""
}

// A summary of a change to the mutable metadata
type GroupUpdated_MetadataFieldChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The field that was changed
	FieldName string `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	// The previous value
	OldValue *string `protobuf:"bytes,2,opt,name=old_value,json=oldValue,proto3,oneof" json:"old_value,omitempty"`
	// The updated value
	NewValue      *string `protobuf:"bytes,3,opt,name=new_value,json=newValue,proto3,oneof" json:"new_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUpdated_MetadataFieldChange) Reset() {
	*x = GroupUpdated_MetadataFieldChange{}
	mi := &file_mls_message_contents_transcript_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUpdated_MetadataFieldChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUpdated_MetadataFieldChange) ProtoMessage() {}

func (x *GroupUpdated_MetadataFieldChange) ProtoReflect() protoreflect.Message {
	mi := &file_mls_message_contents_transcript_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUpdated_MetadataFieldChange.ProtoReflect.Descriptor instead.
func (*GroupUpdated_MetadataFieldChange) Descriptor() ([]byte, []int) {
	return file_mls_message_contents_transcript_messages_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GroupUpdated_MetadataFieldChange) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *GroupUpdated_MetadataFieldChange) GetOldValue() string {
	if x != nil && x.OldValue != nil {
		return *x.OldValue
	}
	return ""
}

func (x *GroupUpdated_MetadataFieldChange) GetNewValue() string {
	if x != nil && x.NewValue != nil {
		return *x.NewValue
	}
	return ""
}

var File_mls_message_contents_transcript_messages_proto protoreflect.FileDescriptor

const file_mls_message_contents_transcript_messages_proto_rawDesc = "" +
	"\n" +
	".mls/message_contents/transcript_messages.proto\x12\x19xmtp.mls.message_contents\"\xa7\x01\n" +
	"\x10MembershipChange\x12)\n" +
	"\x10installation_ids\x18\x01 \x03(\fR\x0finstallationIds\x12'\n" +
	"\x0faccount_address\x18\x02 \x01(\tR\x0eaccountAddress\x12?\n" +
	"\x1cinitiated_by_account_address\x18\x03 \x01(\tR\x19initiatedByAccountAddress\"\x80\x03\n" +
	"\x16GroupMembershipChanges\x12P\n" +
	"\rmembers_added\x18\x01 \x03(\v2+.xmtp.mls.message_contents.MembershipChangeR\fmembersAdded\x12T\n" +
	"\x0fmembers_removed\x18\x02 \x03(\v2+.xmtp.mls.message_contents.MembershipChangeR\x0emembersRemoved\x12\\\n" +
	"\x13installations_added\x18\x03 \x03(\v2+.xmtp.mls.message_contents.MembershipChangeR\x12installationsAdded\x12`\n" +
	"\x15installations_removed\x18\x04 \x03(\v2+.xmtp.mls.message_contents.MembershipChangeR\x14installationsRemoved\"\x9b\x04\n" +
	"\fGroupUpdated\x121\n" +
	"\x15initiated_by_inbox_id\x18\x01 \x01(\tR\x12initiatedByInboxId\x12R\n" +
	"\radded_inboxes\x18\x02 \x03(\v2-.xmtp.mls.message_contents.GroupUpdated.InboxR\faddedInboxes\x12V\n" +
	"\x0fremoved_inboxes\x18\x03 \x03(\v2-.xmtp.mls.message_contents.GroupUpdated.InboxR\x0eremovedInboxes\x12q\n" +
	"\x16metadata_field_changes\x18\x04 \x03(\v2;.xmtp.mls.message_contents.GroupUpdated.MetadataFieldChangeR\x14metadataFieldChanges\x1a\"\n" +
	"\x05Inbox\x12\x19\n" +
	"\binbox_id\x18\x01 \x01(\tR\ainboxId\x1a\x94\x01\n" +
	"\x13MetadataFieldChange\x12\x1d\n" +
	"\n" +
	"field_name\x18\x01 \x01(\tR\tfieldName\x12 \n" +
	"\told_value\x18\x02 \x01(\tH\x00R\boldValue\x88\x01\x01\x12 \n" +
	"\tnew_value\x18\x03 \x01(\tH\x01R\bnewValue\x88\x01\x01B\f\n" +
	"\n" +
	"_old_valueB\f\n" +
	"\n" +
	"_new_valueB\xf0\x01\n" +
	"\x1dcom.xmtp.mls.message_contentsB\x17TranscriptMessagesProtoP\x01Z4github.com/xmtp/xmtpd/pkg/proto/mls/message_contents\xa2\x02\x03XMM\xaa\x02\x18Xmtp.Mls.MessageContents\xca\x02\x18Xmtp\\Mls\\MessageContents\xe2\x02$Xmtp\\Mls\\MessageContents\\GPBMetadata\xea\x02\x1aXmtp::Mls::MessageContentsb\x06proto3"

var (
	file_mls_message_contents_transcript_messages_proto_rawDescOnce sync.Once
	file_mls_message_contents_transcript_messages_proto_rawDescData []byte
)

func file_mls_message_contents_transcript_messages_proto_rawDescGZIP() []byte {
	file_mls_message_contents_transcript_messages_proto_rawDescOnce.Do(func() {
		file_mls_message_contents_transcript_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mls_message_contents_transcript_messages_proto_rawDesc), len(file_mls_message_contents_transcript_messages_proto_rawDesc)))
	})
	return file_mls_message_contents_transcript_messages_proto_rawDescData
}

var file_mls_message_contents_transcript_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mls_message_contents_transcript_messages_proto_goTypes = []any{
	(*MembershipChange)(nil),                 // 0: xmtp.mls.message_contents.MembershipChange
	(*GroupMembershipChanges)(nil),           // 1: xmtp.mls.message_contents.GroupMembershipChanges
	(*GroupUpdated)(nil),                     // 2: xmtp.mls.message_contents.GroupUpdated
	(*GroupUpdated_Inbox)(nil),               // 3: xmtp.mls.message_contents.GroupUpdated.Inbox
	(*GroupUpdated_MetadataFieldChange)(nil), // 4: xmtp.mls.message_contents.GroupUpdated.MetadataFieldChange
}
var file_mls_message_contents_transcript_messages_proto_depIdxs = []int32{
	0, // 0: xmtp.mls.message_contents.GroupMembershipChanges.members_added:type_name -> xmtp.mls.message_contents.MembershipChange
	0, // 1: xmtp.mls.message_contents.GroupMembershipChanges.members_removed:type_name -> xmtp.mls.message_contents.MembershipChange
	0, // 2: xmtp.mls.message_contents.GroupMembershipChanges.installations_added:type_name -> xmtp.mls.message_contents.MembershipChange
	0, // 3: xmtp.mls.message_contents.GroupMembershipChanges.installations_removed:type_name -> xmtp.mls.message_contents.MembershipChange
	3, // 4: xmtp.mls.message_contents.GroupUpdated.added_inboxes:type_name -> xmtp.mls.message_contents.GroupUpdated.Inbox
	3, // 5: xmtp.mls.message_contents.GroupUpdated.removed_inboxes:type_name -> xmtp.mls.message_contents.GroupUpdated.Inbox
	4, // 6: xmtp.mls.message_contents.GroupUpdated.metadata_field_changes:type_name -> xmtp.mls.message_contents.GroupUpdated.MetadataFieldChange
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_mls_message_contents_transcript_messages_proto_init() }
func file_mls_message_contents_transcript_messages_proto_init() {
	if File_mls_message_contents_transcript_messages_proto != nil {
		return
	}
	file_mls_message_contents_transcript_messages_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mls_message_contents_transcript_messages_proto_rawDesc), len(file_mls_message_contents_transcript_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mls_message_contents_transcript_messages_proto_goTypes,
		DependencyIndexes: file_mls_message_contents_transcript_messages_proto_depIdxs,
		MessageInfos:      file_mls_message_contents_transcript_messages_proto_msgTypes,
	}.Build()
	File_mls_message_contents_transcript_messages_proto = out.File
	file_mls_message_contents_transcript_messages_proto_goTypes = nil
	file_mls_message_contents_transcript_messages_proto_depIdxs = nil
}
