#!/usr/bin/env sh
set -e

DOCKER_IMAGE_TAG="${DOCKER_IMAGE_TAG:-dev}"
DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME:-ghcr.io/xmtp/xmtpd}"
VERSION="$(git describe HEAD --tags --long)"

docker buildx build \
    --build-arg="VERSION=${VERSION}" \
    --tag "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" \
    -f dev/docker/Dockerfile \
    .
