#!/usr/bin/env sh
set -e

DOCKER_IMAGE_TAG="${DOCKER_IMAGE_TAG:-dev}"
DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME:-xmtp/xmtpd}"
GIT_COMMIT="$(git rev-parse HEAD)"

docker buildx build \
    --build-arg="GIT_COMMIT=${GIT_COMMIT}" \
    --tag "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" \
    -f dev/docker/Dockerfile \
    .
