services:
  register-node-1:
    platform: linux/amd64
    image: ghcr.io/xmtp/xmtpd-cli:sha-7e2f18f
    profiles: ["single", "dual"]
    env_file:
      - ../local.env
    command:
      [
        "register-node",
        "--http-address=${NODE_1_HTTP_ADDRESS}",
        "--node-owner-address=${ANVIL_ACC_1_ADDRESS}",
        "--node-signing-key-pub=${ANVIL_ACC_1_PUBLIC_KEY}",
        "--admin.private-key=${PRIVATE_KEY}",
      ]
    restart: no
    network_mode: host

  enable-node-1:
    platform: linux/amd64
    image: ghcr.io/xmtp/xmtpd-cli:sha-7e2f18f
    profiles: ["single", "dual"]
    env_file:
      - ../local.env
    command:
      [
        "add-node-to-network",
        "--admin.private-key=${PRIVATE_KEY}",
        "--node-id=100",
      ]
    depends_on:
      register-node-1:
        condition: service_completed_successfully
    restart: no
    network_mode: host

  register-node-2:
    platform: linux/amd64
    image: ghcr.io/xmtp/xmtpd-cli:sha-7e2f18f
    profiles: ["dual"]
    env_file:
      - ../local.env
    command:
      [
        "register-node",
        "--http-address=${NODE_2_HTTP_ADDRESS}",
        "--node-owner-address=${ANVIL_ACC_2_ADDRESS}",
        "--node-signing-key-pub=${ANVIL_ACC_2_PUBLIC_KEY}",
        "--admin.private-key=${PRIVATE_KEY}",
      ]
    depends_on:
      enable-node-1:
        condition: service_completed_successfully
    restart: no
    network_mode: host

  enable-node-2:
    platform: linux/amd64
    image: ghcr.io/xmtp/xmtpd-cli:sha-7e2f18f
    profiles: ["dual"]
    env_file:
      - ../local.env
    command:
      [
        "add-node-to-network",
        "--admin.private-key=${PRIVATE_KEY}",
        "--node-id=200",
      ]
    depends_on:
      register-node-2:
        condition: service_completed_successfully
    restart: no
    network_mode: host
