x-cli-image: &cli-image
  build:
    context: ../../
    dockerfile: ./dev/docker/cli.Dockerfile
  image: ghcr.io/xmtp/xmtpd-cli:dev

services:
  register-node-1:
    <<: *cli-image
    profiles: ["single", "dual"]
    env_file:
      - ../local.env
    command:
      [
        "--config-file=config://anvil",
        "--private-key=${PRIVATE_KEY}",
        "nodes",
        "register",
        "--owner-address=${ANVIL_ACC_1_ADDRESS}",
        "--signing-key-pub=${ANVIL_ACC_1_PUBLIC_KEY}",
        "--http-address=${NODE_1_HTTP_ADDRESS}",
      ]
    restart: "no"
    network_mode: host

  enable-node-1:
    <<: *cli-image
    profiles: ["single", "dual"]
    env_file:
      - ../local.env
    command:
      [
        "--config-file=config://anvil",
        "--private-key=${PRIVATE_KEY}",
        "nodes",
        "canonical-network",
        "--add",
        "--node-id=100",
      ]
    depends_on:
      register-node-1:
        condition: service_completed_successfully
    restart: "no"
    network_mode: host

  register-node-2:
    <<: *cli-image
    profiles: ["dual"]
    env_file:
      - ../local.env
    command:
      [
        "--config-file=config://anvil",
        "--private-key=${PRIVATE_KEY}",
        "nodes",
        "register",
        "--owner-address=${ANVIL_ACC_2_ADDRESS}",
        "--signing-key-pub=${ANVIL_ACC_2_PUBLIC_KEY}",
        "--http-address=${NODE_2_HTTP_ADDRESS}",
      ]
    depends_on:
      enable-node-1:
        condition: service_completed_successfully
    restart: "no"
    network_mode: host

  enable-node-2:
    <<: *cli-image
    profiles: ["dual"]
    env_file:
      - ../local.env
    command:
      [
        "--config-file=config://anvil",
        "--private-key=${PRIVATE_KEY}",
        "nodes",
        "canonical-network",
        "--add",
        "--node-id=200",
      ]
    depends_on:
      register-node-2:
        condition: service_completed_successfully
    restart: "no"
    network_mode: host
