services:
  node:
    build:
      context: ../..
      dockerfile: dev/docker/Dockerfile
      args:
        VERSION: "0.2.1-dev"
    env_file:
      - .xmtpd_env
    environment:
      XMTPD_REFLECTION_ENABLE: "true"
      XMTPD_PAYER_ENABLE: "true"
      XMTPD_REPLICATION_ENABLE: "true"
      XMTPD_SYNC_ENABLE: "true"
      XMTPD_INDEXER_ENABLE: "true"
      XMTPD_METRICS_ENABLE: "true"
      XMTPD_METRICS_METRICS_ADDRESS: "0.0.0.0"
    ports:
      - 5050:5050
      - 8008:8008

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Viewer
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer

volumes:
  grafana_data: