global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "host.docker.internal:8008"
          - "host.docker.internal:8009"
  - job_name: xmtpd
    static_configs:
      - targets:
          - "node:8008"