#!/bin/bash
set -eo pipefail

if [ -z "$1" ]; then
  profile="single"
  echo "No profile provided, defaulting to single"
elif [ "$1" = "single" ] || [ "$1" = "dual" ]; then
  profile="$1"
else
  echo "Invalid profile '$1', defaulting to single"
  profile="single"
fi


docker compose \
  -f dev/docker/docker-compose.yml \
  --env-file dev/local.env \
  --profile "${profile}" \
  -p "xmtpd" \
  up -d \
  --remove-orphans \
  --wait

docker compose \
  -f dev/docker/docker-compose-register.yml \
  --env-file dev/local.env \
  --profile "${profile}" \
  -p "xmtpd_register_nodes" \
  build \
  register-node-1

docker compose \
  -f dev/docker/docker-compose-register.yml \
  --env-file dev/local.env \
  --profile "${profile}" \
  -p "xmtpd_register_nodes" \
  up \
  --remove-orphans

echo
