#!/bin/bash
set -eo pipefail

profile=${1:-single}

if [ "$1" = "single" ]; then
  profile="single"
elif [ "$1" = "dual" ]; then
  profile="dual"
else
  echo "No profile provided, defaulting to single"
fi

docker compose \
  -f dev/docker/docker-compose.yml \
  --env-file dev/local.env \
  -p "xmtpd" \
  up -d \
  --remove-orphans \
  --wait

docker compose \
  -f dev/docker/docker-compose-register.yml \
  --env-file dev/local.env \
  --profile ${profile} \
  -p "xmtpd_register_nodes" \
  up \
  --remove-orphans

echo
