#!/bin/bash
set -euo pipefail

error() {
  echo "Error: $1" >&2
  exit 1
}

# Get the directory where the script is located
SCRIPT_DIR=$(dirname "$(realpath "$0")")

TOP_LEVEL_DIR=$(realpath "${SCRIPT_DIR}/../.." 2>/dev/null) || error "Failed to resolve top-level directory"

[ -d "$TOP_LEVEL_DIR" ] || error "Top level directory not found: $TOP_LEVEL_DIR"

cd "$TOP_LEVEL_DIR" || error "Failed to change to top level directory"

. dev/local.env

export XMTPD_CONTRACTS_RPC_URL=http://chain:8545
export XMTPD_MLS_VALIDATION_GRPC_ADDRESS=http://validation:50051
export XMTPD_DB_WRITER_CONNECTION_STRING=postgres://postgres:xmtp@db:5432/postgres?sslmode=disable

env | grep XMTPD > $SCRIPT_DIR/.xmtpd_env

docker compose -f dev/docker/docker-compose.yml -f dev/docker/node-with-monitoring.yml -p xmtpd up -d --remove-orphans --wait